/** @type {import('tailwindcss').Config} */

module.exports = {
   darkMode: ['class'],
   content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],

   safelist: [
      'bg-primary',
      'text-secondary',
      {
         pattern:
            /bg-theme-(red|green|blue|yellow|mint|teal|orange|purple|pink|turquoise|magenta|olive|maroon|beige|coral|lavender|peach|bronze|taupe|lilac|zinc)/,
      },
      'bg-button-red',
      'bg-button-green',
      'bg-button-blue',
      'bg-button-yellow',
      'bg-status-active',
      'bg-status-onhold',
      'bg-status-completed',
      'bg-status-cancelled',
      'bg-deadline-soon',
      'bg-deadline-past',
      'bg-document-invoice',
      'bg-document-quotation',
      'bg-document-receipt',
      'bg-constant-primary',
      'bg-constant-secondary',
      'bg-constant-tertiary',
      'bg-constant-quartenary',
      'bg-background',
      'bg-foreground',
      'bg-primary-foreground',
      'bg-secondary-foreground',
      'bg-tertiary',
      'bg-quaternary',
      'bg-header',
      'bg-header-dark',
      'bg-card',
      'bg-card-foreground',
      'bg-popover',
      'bg-popover-foreground',
      'bg-muted',
      'bg-muted-foreground',
      'bg-accent',
      'bg-accent-foreground',
      'bg-destructive',
      'bg-destructive-foreground',
      'bg-input',
      'ring-ring',
      'bg-chart-1',
      'bg-chart-2',
      'bg-chart-3',
      'bg-chart-4',
      'bg-chart-5',
   ],
   theme: {
      extend: {
         utilities: {
            '.writing-vertical-rl': {
               writingMode: 'vertical-rl',
            },
         },
         animation: {
            shake: 'shake 0.3s ease-in-out',
            blink: 'fadeInOut 2.5s ease-in-out infinite',
         },
         keyframes: {
            blink: {
               '50%': { opacity: '0' },
            },
            shake: {
               '0%, 100%': { transform: 'translateX(0)' },
               '25%': { transform: 'translateX(-2px)' },
               '50%': { transform: 'translateX(2px)' },
               '75%': { transform: 'translateX(-2px)' },
            },
         },
         screens: {
            sm: { max: '1179px' },
            md: { min: '1180px', max: '1279px' },
            lg: { min: '1280px', max: '1600px' },
            xl: { min: '1600px' },
         },
         fontFamily: {
            sans: ['Lexend'],
            thai: ['PrachasornNeue'],
         },
         borderRadius: {
            lg: 'var(--radius)',
            md: 'calc(var(--radius) - 2px)',
            sm: 'calc(var(--radius) - 4px)',
            container: '15px'
         },
         colors: {
            general: {
               red: 'var(--freelanceman-general-red)',
               yellow: 'var(--freelanceman-general-yellow)',
               blue: 'var(--freelanceman-general-blue)',
            },
            theme: {
               base: 'var(--freelanceman-theme-base)',
               red: 'var(--freelanceman-theme-red)',
               green: 'var(--freelanceman-theme-green)',
               blue: 'var(--freelanceman-theme-blue)',
               yellow: 'var(--freelanceman-theme-yellow)',
               mint: 'var(--freelanceman-theme-mint)',
               teal: 'var(--freelanceman-theme-teal)',
               orange: 'var(--freelanceman-theme-orange)',
               purple: 'var(--freelanceman-theme-purple)',
               pink: 'var(--freelanceman-theme-pink)',
               turquoise: 'var(--freelanceman-theme-turquoise)',
               magenta: 'var(--freelanceman-theme-magenta)',
               olive: 'var(--freelanceman-theme-olive)',
               maroon: 'var(--freelanceman-theme-maroon)',
               beige: 'var(--freelanceman-theme-beige)',
               coral: 'var(--freelanceman-theme-coral)',
               lavender: 'var(--freelanceman-theme-lavender)',
               peach: 'var(--freelanceman-theme-peach)',
               bronze: 'var(--freelanceman-theme-bronze)',
               taupe: 'var(--freelanceman-theme-taupe)',
               lilac: 'var(--freelanceman-theme-lilac)',
               zinc: 'var(--freelanceman-theme-zinc)',
               grey: 'var(--freelanceman-theme-grey)',
            },
            button: {
               red: 'var(--freelanceman-button-red)',
               green: 'var(--freelanceman-button-green)',
               blue: 'var(--freelanceman-button-blue)',
               yellow: 'var(--freelanceman-button-yellow)',
            },
            status: {
               active: 'var(--freelanceman-status-active)',
               onhold: 'var(--freelanceman-status-onhold)',
               completed: 'var(--freelanceman-status-completed)',
               cancelled: 'var(--freelanceman-status-cancelled)',
            },
            deadline: {
               soon: 'var(--freelanceman-deadline-soon)',
               past: 'var(--freelanceman-deadline-past)',
            },

            document: {
               invoice: 'var(--freelanceman-document-invoice)',
               quotation: 'var(--freelanceman-document-quotation)',
               receipt: 'var(--freelanceman-document-receipt)',
            },
            constant: {
               primary: 'hsl(var(--freelanceman-constant-primary))',
               secondary: 'hsl(var(--freelanceman-constant-secondary))',
               tertiary: 'hsl(var(--freelanceman-constant-tertiary))',
               quartenary: 'hsl(var(--freelanceman-constant-quartenary))',
            },
            background: 'hsl(var(--background))',
            foreground: 'hsl(var(--foreground))',
            primary: {
               DEFAULT: 'hsl(var(--primary))',
               foreground: 'hsl(var(--primary-foreground))',
            },
            secondary: {
               DEFAULT: 'hsl(var(--secondary))',
               foreground: 'hsl(var(--secondary-foreground))',
            },
            tertiary: 'hsl(var(--tertiary))',
            quaternary: 'hsl(var(--quaternary))',
            header: {
               DEFAULT: '#F8F8F8',
               dark: '#262626',
            },
            card: {
               DEFAULT: 'hsl(var(--card))',
               foreground: 'hsl(var(--card-foreground))',
            },
            popover: {
               DEFAULT: 'hsl(var(--popover))',
               foreground: 'hsl(var(--popover-foreground))',
            },
            muted: {
               DEFAULT: 'hsl(var(--muted))',
               foreground: 'hsl(var(--muted-foreground))',
            },
            accent: {
               DEFAULT: 'hsl(var(--accent))',
               foreground: 'hsl(var(--accent-foreground))',
            },
            destructive: {
               DEFAULT: 'hsl(var(--destructive))',
               foreground: 'hsl(var(--destructive-foreground))',
            },
            border: 'hsl(var(--border))',
            input: 'hsl(var(--input))',
            ring: 'hsl(var(--ring))',
            chart: {
               1: 'hsl(var(--chart-1))',
               2: 'hsl(var(--chart-2))',
               3: 'hsl(var(--chart-3))',
               4: 'hsl(var(--chart-4))',
               5: 'hsl(var(--chart-5))',
            },
         },
         fontSize: {
            DEFAULT: '14px',
            '2xl': '33px',
            xl: '25px',
            lg: '19px',
            md: '16px',
            base: '14px',
            sm: '12px',
         },
         borderOpacity: {
            10: '0.1',
            20: '0.2',
            95: '0.95',
         },
      },
   },
   plugins: [
      require('tailwindcss-animate'),
      function ({ addBase }) {
         addBase({
            'html[lang="en"]': { fontFamily: 'Lexend' },
            'html[lang="th"]': { fontFamily: 'PrachasornNeue' },
         });
      },
   ],
};
