import { z } from 'zod';

export const createSalesDocumentSchema = z.object({
    title: z.string().min(1),
    category: z.string().min(1),
    number: z.string().min(1),
    issuedAt: z.string().datetime(),
    currency: z.string().min(1),
    projectId: z.string().uuid(),
    referenceNumber: z.string().min(1),
    projectDescription: z.string().min(1),
    selectedProjectClientId: z.string().uuid(),
    freelancerName: z.string().min(1),
    freelancerEmail: z.string().email(),
    freelancerPhone: z.string().min(1),
    freelancerTaxId: z.string().min(1),
    freelancerDetail: z.string().optional(),
    clientId: z.string().min(1).optional(),
    clientName: z.string().min(1),
    clientTaxId: z.string().min(1),
    clientAddress: z.string().optional(),
    clientPhone: z.string().optional(),
    clientOffice: z.string().optional(),
    clientDetail: z.string().optional(),
    subtotal: z.number(),
    discount: z.number().optional(),
    tax: z.number(),
    total: z.number(),
    customAdjustment: z.number().optional(),
    note: z.string().optional(),
});

export const salesDocumentFilterSchema = z.object({
    title: z.string().min(1).optional(),
    category: z.string().min(1).optional(),
    projectId: z.string().uuid().optional(),
    selectedProjectClientId: z.string().uuid().optional(),
});

export const editSalesDocumentSchema = z.object({
    id: z.string().uuid(),
    title: z.string().min(1).optional(),
    category: z.string().min(1).optional(),
    number: z.string().min(1).optional(),
    issuedAt: z.string().datetime().optional(),
    currency: z.string().min(1).optional(),
    projectId: z.string().uuid().optional(),
    referenceNumber: z.string().min(1).optional(),
    projectDescription: z.string().min(1).optional(),
    selectedProjectClientId: z.string().uuid().optional(),
    freelancerName: z.string().min(1).optional(),
    freelancerEmail: z.string().email().optional(),
    freelancerPhone: z.string().min(1).optional(),
    freelancerTaxId: z.string().min(1).optional(),
    freelancerDetail: z.string().optional(),
    clientId: z.string().uuid().optional(),
    clientName: z.string().min(1).optional(),
    clientTaxId: z.string().min(1).optional(),
    clientAddress: z.string().optional(),
    clientPhone: z.string().optional(),
    clientOffice: z.string().optional(),
    clientDetail: z.string().optional(),
    subtotal: z.number().optional(),
    discount: z.number().optional(),
    tax: z.number().optional(),
    total: z.number().optional(),
    customAdjustment: z.number().optional(),
    note: z.string().optional(),
});

export const salesDocumentPayloadSchema = z.object({
    id: z.string().uuid(),
    userId: z.string(),
    title: z.string().min(1),
    category: z.string().min(1),
    number: z.string().min(1),
    issuedAt: z.string(),
    currency: z.string().min(1),
    projectId: z.string(),
    referenceNumber: z.string().min(1),
    projectDescription: z.string().min(1),
    selectedProjectClientId: z.string(),
    freelancerName: z.string().min(1),
    freelancerEmail: z.string().email(),
    freelancerPhone: z.string().min(1),
    freelancerTaxId: z.string().min(1),
    freelancerDetail: z.string().optional(),
    clientId: z.string(),
    clientName: z.string().min(1),
    clientTaxId: z.string().min(1),
    clientAddress: z.string().optional(),
    clientPhone: z.string().optional(),
    clientOffice: z.string().optional(),
    clientDetail: z.string().optional(),
    subtotal: z.number(),
    discount: z.number().optional(),
    tax: z.number(),
    total: z.number(),
    customAdjustment: z.number().optional(),
    note: z.string().optional(),
    generatedFileId: z.string().optional(),
    createdAt: z.string(),
    updatedAt: z.string(),
});

export type SalesDocumentPayload = z.infer<typeof salesDocumentPayloadSchema>;
export type SalesDocumentFilterDto = z.infer<typeof salesDocumentFilterSchema>;
export type EditSalesDocumentDto = z.infer<typeof editSalesDocumentSchema>;
export type CreateSalesDocumentDto = z.infer<typeof createSalesDocumentSchema>;
