import { z } from 'zod';
import { optionalString } from './helper/optional';
import { filePayloadSchema } from './file.schema';
import { salesDocumentItemSchema } from './sales-document-item.schema';

export const createSalesDocumentSchema = z.object({
    title: z.string().min(1),
    category: z.string().min(1),
    number: z.string().min(1),
    issuedAt: z.string().datetime(),
    currency: z.string().min(1),
    projectId: z.string().uuid(),
    referenceNumber: z.string().min(1),
    projectDescription: z.string().min(1),
    selectedProjectClientId: z.string().uuid(),
    freelancerName: z.string().min(1),
    freelancerEmail: z.string().email(),
    freelancerPhone: z.string().min(1),
    freelancerTaxId: z.string().min(1),
    freelancerDetail: optionalString(),
    freelancerAddress: optionalString(),
    clientId: z.string().min(1).optional(),
    clientName: z.string().min(1),
    clientTaxId: z.string().min(1),
    clientAddress: optionalString(),
    clientPhone: optionalString(),
    clientOffice: optionalString(),
    clientDetail: optionalString(),
    subtotal: z.number(),
    discount: z.number().optional(),
    tax: z.number(),
    total: z.number(),
    discountPercent: z.number().optional(),
    discountFlat: z.number().optional(),
    note: optionalString(),
});

export const salesDocumentFilterSchema = z.object({
    title: z.string().min(1).optional(),
    category: z.string().min(1).optional(),
    projectId: z.string().uuid().optional(),
    selectedProjectClientId: z.string().uuid().optional(),
});

export const editSalesDocumentSchema = z.object({
    id: z.string().uuid(),
    title: z.string().min(1).optional(),
    category: z.string().min(1).optional(),
    number: z.string().min(1).optional(),
    issuedAt: z.string().datetime().optional(),
    currency: z.string().min(1).optional(),
    projectId: z.string().uuid().optional(),
    referenceNumber: z.string().min(1).optional(),
    projectDescription: z.string().min(1).optional(),
    selectedProjectClientId: z.string().uuid().optional(),
    freelancerName: z.string().min(1).optional(),
    freelancerEmail: z.string().email().optional(),
    freelancerPhone: z.string().min(1).optional(),
    freelancerTaxId: z.string().min(1).optional(),
    freelancerDetail: optionalString(),
    freelancerAddress: optionalString(),
    clientId: z.string().uuid().optional(),
    clientName: z.string().min(1).optional(),
    clientTaxId: z.string().min(1).optional(),
    clientAddress: optionalString(),
    clientPhone: optionalString(),
    clientOffice: optionalString(),
    clientDetail: optionalString(),
    subtotal: z.number().optional(),
    discount: z.number().optional(),
    tax: z.number().optional(),
    total: z.number().optional(),
    discountPercent: z.number().optional(),
    discountFlat: z.number().optional(),
    note: optionalString(),
});

export const salesDocumentPayloadSchema = z.object({
    id: z.string().uuid(),
    userId: z.string(),
    title: z.string().min(1),
    category: z.string().min(1),
    number: z.string().min(1),
    issuedAt: z.string(),
    currency: z.string().min(1),
    projectId: z.string(),
    referenceNumber: z.string().min(1),
    projectDescription: z.string().min(1),
    selectedProjectClientId: z.string(),
    freelancerName: z.string().min(1),
    freelancerEmail: z.string().email(),
    freelancerPhone: z.string().min(1),
    freelancerTaxId: z.string().min(1),
    freelancerDetail: optionalString(),
    freelancerAddress: optionalString(),
    clientId: z.string(),
    clientName: z.string().min(1),
    clientTaxId: z.string().min(1),
    clientAddress: optionalString(),
    clientPhone: optionalString(),
    clientOffice: optionalString(),
    clientDetail: optionalString(),
    subtotal: z.number(),
    discount: z.number().optional(),
    tax: z.number(),
    total: z.number(),
    discountPercent: z.number().optional(),
    discountFlat: z.number().optional(),
    note: optionalString(),
    generatedFileId: optionalString(),
    createdAt: z.string(),
    updatedAt: z.string(),
    file: filePayloadSchema,
    items: z.array(salesDocumentItemSchema)
});

export const createPdfSchema = z.object({
    id: z.string().uuid(),
    userId: z.string(),
    title: z.string().min(1),
    category: z.string().min(1),
    number: z.string().min(1),
    issuedAt: z.string(),
    currency: z.string().min(1),
    projectId: z.string(),
    referenceNumber: z.string().min(1),
    projectDescription: z.string().min(1),
    selectedProjectClientId: z.string(),
    freelancerName: z.string().min(1),
    freelancerEmail: z.string().email(),
    freelancerPhone: z.string().min(1),
    freelancerTaxId: z.string().min(1),
    freelancerDetail: optionalString(),
    freelancerAddress: optionalString(),
    clientId: z.string(),
    clientName: z.string().min(1),
    clientTaxId: z.string().min(1),
    clientAddress: optionalString(),
    clientPhone: optionalString(),
    clientOffice: optionalString(),
    clientDetail: optionalString(),
    subtotal: z.number(),
    discount: z.number().optional(),
    tax: z.number(),
    total: z.number(),
    discountPercent: z.number().optional(),
    discountFlat: z.number().optional(),
    note: optionalString(),
    generatedFileId: optionalString(),
    createdAt: z.string(),
    updatedAt: z.string(),
    items: z.array(salesDocumentItemSchema)
});


export type SalesDocumentPayload = z.infer<typeof salesDocumentPayloadSchema>;
export type SalesDocumentFilterDto = z.infer<typeof salesDocumentFilterSchema>;
export type EditSalesDocumentDto = z.infer<typeof editSalesDocumentSchema>;
export type CreateSalesDocumentDto = z.infer<typeof createSalesDocumentSchema>;
export type CreatePdfDto = z.infer<typeof createPdfSchema>;