export const getPartnerContacts = (userId: string) => {
    return [
        {
            userId: userId,
            name: 'Niran Taylor',
            company: 'PixelCraft Studios',
            role: 'Lead Designer',
            phoneNumber: '081-234-5678',
            email: 'niran.taylor@pixelcraft.com',
            details: 'Specializes in UI/UX design.',
            avatar: 'https://example.com/avatars/niran.jpg',
        },
        {
            userId: userId,
            name: 'Pimchanok Miller',
            company: 'VividStream Media',
            role: 'Content Strategist',
            phoneNumber: '082-345-6789',
            email: 'pimchanok.miller@vividstream.net',
            details: 'Expert in digital content creation.',
            avatar: 'https://example.com/avatars/pimchanok.jpg',
        },
        {
            userId: userId,
            name: 'Akara Davis',
            company: 'SynthWave Creative',
            role: 'Motion Graphics Artist',
            phoneNumber: '083-456-7890',
            email: 'akara.davis@synthwave.co',
            details: 'Creates stunning visual effects.',
            avatar: 'https://example.com/avatars/akara.jpg',
        },
        {
            userId: userId,
            name: 'Chayaporn Wilson',
            company: 'DreamForge Labs',
            role: 'Brand Consultant',
            phoneNumber: '084-567-8901',
            email: 'chayaporn.wilson@dreamforge.org',
            details: 'Develops impactful brand identities.',
            avatar: 'https://example.com/avatars/chayaporn.jpg',
        },
        {
            userId: userId,
            name: 'Thanawat Brown',
            company: 'EchoBloom Productions',
            role: 'Video Producer',
            phoneNumber: '085-678-9012',
            email: 'thanawat.brown@echobloom.tv',
            details: 'Experienced in short film production.',
            avatar: 'https://example.com/avatars/thanawat.jpg',
        },
        {
            userId: userId,
            name: 'Kanyarat Jones',
            company: 'NeonSpire Studios',
            role: 'Illustrator',
            phoneNumber: '086-789-0123',
            email: 'kanyarat.jones@neonspire.art',
            details: 'Specializes in digital illustrations.',
            avatar: 'https://example.com/avatars/kanyarat.jpg',
        },
        {
            userId: userId,
            name: 'Sopon Garcia',
            company: 'QuantumLeap Design',
            role: 'Product Designer',
            phoneNumber: '087-890-1234',
            email: 'sopon.garcia@quantumleap.tech',
            details: 'Focuses on user-centric product design.',
            avatar: 'https://example.com/avatars/sopon.jpg',
        },
        {
            userId: userId,
            name: 'Napat Rodriguez',
            company: 'AuraFlow Creative',
            role: 'Art Director',
            phoneNumber: '088-901-2345',
            email: 'napat.rodriguez@auraflow.com',
            details: 'Oversees visual style and images.',
            avatar: 'https://example.com/avatars/napat.jpg',
        },
        {
            userId: userId,
            name: 'Saranya Martinez',
            company: 'StellarGlow Agency',
            role: 'Social Media Manager',
            phoneNumber: '089-012-3456',
            email: 'saranya.martinez@stellarglow.co',
            details: 'Manages online presence and campaigns.',
            avatar: 'https://example.com/avatars/saranya.jpg',
        },
        {
            userId: userId,
            name: 'Teerawat Hernandez',
            company: 'ChronosInk Studio',
            role: 'Web Developer',
            phoneNumber: '090-123-4567',
            email: 'teerawat.hernandez@chronosink.dev',
            details: 'Builds responsive web applications.',
            avatar: 'https://example.com/avatars/teerawat.jpg',
        },
        {
            userId: userId,
            name: 'Supaporn Lopez',
            company: 'CrimsonVerse Media',
            role: 'Copywriter',
            phoneNumber: '091-234-5678',
            email: 'supaporn.lopez@crimsonverse.com',
            details: 'Crafts compelling narratives.',
            avatar: 'https://example.com/avatars/supaporn.jpg',
        },
        {
            userId: userId,
            name: 'Adul Gonzalez',
            company: 'Solstice Labs',
            role: 'Game Designer',
            phoneNumber: '092-345-6789',
            email: 'adul.gonzalez@solstice.games',
            details: 'Designs immersive game experiences.',
            avatar: 'https://example.com/avatars/adul.jpg',
        },
        {
            userId: userId,
            name: 'Ploypailin Perez',
            company: 'NebulaNest Studio',
            role: 'Photographer',
            phoneNumber: '093-456-7890',
            email: 'ploypailin.perez@nebulanest.photo',
            details: 'Captures stunning visual stories.',
            avatar: 'https://example.com/avatars/ploypailin.jpg',
        },
        {
            userId: userId,
            name: 'Chaiyut Sanchez',
            company: 'IgnitePulse Creative',
            role: 'Music Producer',
            phoneNumber: '094-567-8901',
            email: 'chaiyut.sanchez@ignitepulse.audio',
            details: 'Composes and produces original music.',
            avatar: 'https://example.com/avatars/chaiyut.jpg',
        },
        {
            userId: userId,
            name: 'Duangporn Rivera',
            company: 'EmberEcho Collective',
            role: 'Fashion Designer',
            phoneNumber: '095-678-9012',
            email: 'duangporn.rivera@emberecho.fashion',
            details: 'Creates innovative apparel designs.',
            avatar: 'https://example.com/avatars/duangporn.jpg',
        },
        {
            userId: userId,
            name: 'Kittisak Torres',
            company: 'BloomPixel Innovators',
            role: 'UX Researcher',
            phoneNumber: '096-789-0123',
            email: 'kittisak.torres@bloompixel.io',
            details: 'Conducts user research for product improvement.',
            avatar: 'https://example.com/avatars/kittisak.jpg',
        },
        {
            userId: userId,
            name: 'Sukanya Scott',
            company: 'CrystalByte Solutions',
            role: 'Data Visualization Specialist',
            phoneNumber: '097-890-1234',
            email: 'sukanya.scott@crystalbyte.ai',
            details: 'Transforms complex data into visual insights.',
            avatar: 'https://example.com/avatars/sukanya.jpg',
        },
        {
            userId: userId,
            name: 'Pornchai Green',
            company: 'ShadowMeld Studios',
            role: 'Concept Artist',
            phoneNumber: '098-901-2345',
            email: 'pornchai.green@shadowmeld.art',
            details: 'Develops visual concepts for games and films.',
            avatar: 'https://example.com/avatars/pornchai.jpg',
        },
        {
            userId: userId,
            name: 'Warunee Adams',
            company: 'ZenithCode Ventures',
            role: 'Software Engineer (Creative Tools)',
            phoneNumber: '099-012-3456',
            email: 'warunee.adams@zenithcode.dev',
            details: 'Builds tools for creative professionals.',
            avatar: 'https://example.com/avatars/warunee.jpg',
        },
        {
            userId: userId,
            name: 'Boonrawd Baker',
            company: 'PixelPulse Collective',
            role: 'Animator',
            phoneNumber: '080-123-4567',
            email: 'boonrawd.baker@pixelpulse.anim',
            details: 'Brings characters and stories to life.',
            avatar: 'https://example.com/avatars/boonrawd.jpg',
        },
        {
            userId: userId,
            name: 'Somsak White',
            company: 'Freelancer',
            role: 'Graphic Designer',
            phoneNumber: '081-333-4444',
            email: 'somsak.w@example.com',
            details: 'Specializes in logo and branding design.',
            avatar: 'https://example.com/avatars/somsak.jpg',
        },
        {
            userId: userId,
            name: 'Naree King',
            company: 'Freelancer',
            role: 'Web Designer',
            phoneNumber: '082-444-5555',
            email: 'naree.k@example.com',
            details: 'Focuses on responsive and modern web interfaces.',
            avatar: 'https://example.com/avatars/naree.jpg',
        },
        {
            userId: userId,
            name: 'Supachai Wright',
            company: 'Freelancer',
            role: 'Illustrator',
            phoneNumber: '083-555-6666',
            email: 'supachai.w@example.com',
            details: 'Known for unique digital art and character design.',
            avatar: 'https://example.com/avatars/supachai.jpg',
        },
        {
            userId: userId,
            name: 'Malee Hill',
            company: 'Freelancer',
            role: 'Content Writer',
            phoneNumber: '084-666-7777',
            email: 'malee.h@example.com',
            details: 'Creates engaging articles and blog posts.',
            avatar: 'https://example.com/avatars/malee.jpg',
        },
        {
            userId: userId,
            name: 'Pichai Green',
            company: 'Freelancer',
            role: 'Video Editor',
            phoneNumber: '085-777-8888',
            email: 'pichai.g@example.com',
            details:
                'Produces high-quality video content for various platforms.',
            avatar: 'https://example.com/avatars/pichai.jpg',
        },
        {
            userId: userId,
            name: 'Thida Adams',
            company: 'Freelancer',
            role: 'Social Media Strategist',
            phoneNumber: '086-888-9999',
            email: 'thida.a@example.com',
            details: 'Develops and executes social media campaigns.',
            avatar: 'https://example.com/avatars/thida.jpg',
        },
        {
            userId: userId,
            name: 'Adisak Baker',
            company: 'Freelancer',
            role: 'Photographer',
            phoneNumber: '087-999-0000',
            email: 'adisak.b@example.com',
            details: 'Specializes in portrait and event photography.',
            avatar: 'https://example.com/avatars/adisak.jpg',
        },
        {
            userId: userId,
            name: 'Chantana Nelson',
            company: 'Freelancer',
            role: 'UX/UI Designer',
            phoneNumber: '088-000-1111',
            email: 'chantana.n@example.com',
            details: 'Designs intuitive and user-friendly interfaces.',
            avatar: 'https://example.com/avatars/chantana.jpg',
        },
        {
            userId: userId,
            name: 'Wichai Carter',
            company: 'Freelancer',
            role: 'Animator',
            phoneNumber: '089-111-2222',
            email: 'wichai.c@example.com',
            details: 'Creates 2D and 3D animations for various projects.',
            avatar: 'https://example.com/avatars/wichai.jpg',
        },
        {
            userId: userId,
            name: 'Sarinporn Mitchell',
            company: 'Freelancer',
            role: 'Marketing Consultant',
            phoneNumber: '090-222-3333',
            email: 'sarinporn.m@example.com',
            details: 'Provides strategic marketing advice and solutions.',
            avatar: 'https://example.com/avatars/sarinporn.jpg',
        },
        {
            userId: userId,
            name: 'Pongsak Perez',
            company: 'Freelancer',
            role: 'Sound Designer',
            phoneNumber: '091-333-4444',
            email: 'pongsak.p@example.com',
            details: 'Creates and mixes audio for video and games.',
            avatar: 'https://example.com/avatars/pongsak.jpg',
        },
        {
            userId: userId,
            name: 'Kanokwan Roberts',
            company: 'Freelancer',
            role: 'Copy Editor',
            phoneNumber: '092-444-5555',
            email: 'kanokwan.r@example.com',
            details: 'Ensures clarity, consistency, and accuracy in text.',
            avatar: 'https://example.com/avatars/kanokwan.jpg',
        },
        {
            userId: userId,
            name: 'Chayanna Turner',
            company: 'Freelancer',
            role: 'SEO Specialist',
            phoneNumber: '093-555-6666',
            email: 'chayanna.t@example.com',
            details: 'Optimizes content for search engine visibility.',
            avatar: 'https://example.com/avatars/chayanna.jpg',
        },
        {
            userId: userId,
            name: 'Jirayu Phillips',
            company: 'Freelancer',
            role: 'Illustrator',
            phoneNumber: '094-666-7777',
            email: 'jirayu.p@example.com',
            details: "Specializes in children's book illustrations.",
            avatar: 'https://example.com/avatars/jirayu.jpg',
        },
        {
            userId: userId,
            name: 'Anchalee Campbell',
            company: 'Freelancer',
            role: 'Proofreader',
            phoneNumber: '095-777-8888',
            email: 'anchalee.c@example.com',
            details: 'Performs final checks for grammar and spelling errors.',
            avatar: 'https://example.com/avatars/anchalee.jpg',
        },
        {
            userId: userId,
            name: 'Preecha Parker',
            company: 'Freelancer',
            role: '3D Modeler',
            phoneNumber: '096-888-9999',
            email: 'preecha.p@example.com',
            details: 'Creates realistic 3D models for various industries.',
            avatar: 'https://example.com/avatars/preecha.jpg',
        },
        {
            userId: userId,
            name: 'Yupin Evans',
            company: 'Freelancer',
            role: 'Voice Over Artist',
            phoneNumber: '097-999-0000',
            email: 'yupin.e@example.com',
            details:
                'Provides professional voice-overs for commercials and narrations.',
            avatar: 'https://example.com/avatars/yupin.jpg',
        },
        {
            userId: userId,
            name: 'Sarawut Edwards',
            company: 'Freelancer',
            role: 'Photoshop Retoucher',
            phoneNumber: '098-000-1111',
            email: 'sarawut.e@example.com',
            details: 'Enhances and manipulates images for various purposes.',
            avatar: 'https://example.com/avatars/sarawut.jpg',
        },
        {
            userId: userId,
            name: 'Benjaporn Collins',
            company: 'Freelancer',
            role: 'E-learning Developer',
            phoneNumber: '099-111-2222',
            email: 'benjaporn.c@example.com',
            details: 'Develops interactive and engaging online courses.',
            avatar: 'https://example.com/avatars/benjaporn.jpg',
        },
        {
            userId: userId,
            name: 'Anan Stewart',
            company: 'Freelancer',
            role: 'CRM Specialist',
            phoneNumber: '080-222-3333',
            email: 'anan.s@example.com',
            details:
                'Manages customer relationships and optimizes sales processes.',
            avatar: 'https://example.com/avatars/anan.jpg',
        },
    ];
};
