export const seedClientsData = [
    {
        name: 'Aura Tea Co',
        taxId: '123-456-7890',
        email: 'info@auratea.com',
        phoneNumber: '+1-555-123-4567',
        address: '123 Tea Leaf Lane, Serenity City, CA 90210',
        detail: 'Premium organic tea distributor specializing in unique blends.',
        themeColor: 'peach',
    },
    {
        name: 'Urban Flow Fitness',
        taxId: '098-765-4321',
        email: 'contact@urbanflow.fit',
        phoneNumber: '+1-555-987-6543',
        address: '456 Gym Ave, Metropolis, NY 10001',
        detail: 'Modern fitness center offering diverse classes and personal training.',
        themeColor: 'olive',
    },
    {
        name: 'ByteNest Tech Solutions',
        taxId: '112-233-4455',
        email: 'support@bytenest.io',
        phoneNumber: '+1-555-222-3333',
        address: '789 Silicon Valley Blvd, Tech City, CA 94043',
        detail: 'Innovative software development and IT consulting firm.',
        themeColor: 'yellow',
    },
    {
        name: 'Golden Spoon Eatery',
        taxId: '556-677-8899',
        email: 'reservations@goldenspoon.com',
        phoneNumber: '+1-555-444-5555',
        address: '101 Gourmet St, Foodie Town, TX 75001',
        detail: 'Fine dining restaurant with a focus on seasonal, locally sourced ingredients.',
        themeColor: 'mint',
    },
    {
        name: 'Harmony Music Academy',
        taxId: '221-144-3366',
        email: 'admissions@harmonymusic.edu',
        phoneNumber: '+1-555-666-7777',
        address: '202 Melody Lane, Artville, OR 97201',
        detail: 'Music school offering lessons in various instruments and vocal training.',
        themeColor: 'pink',
    },
    {
        name: 'Horizon Real Estate Group',
        taxId: '778-899-0011',
        email: 'info@horizonrealty.com',
        phoneNumber: '+1-555-888-9999',
        address: '303 Property Rd, Estateville, FL 33101',
        detail: 'Comprehensive real estate services for residential and commercial properties.',
        themeColor: 'lilac',
    },
    {
        name: 'Eco-Glide Electric Scooters',
        taxId: '334-455-6677',
        email: 'sales@ecoglide.co',
        phoneNumber: '+1-555-111-2222',
        address: '404 Green Mobility Dr, Eco City, WA 98101',
        detail: 'Distributor and rental service for eco-friendly electric scooters.',
        themeColor: 'bronze',
    },
    {
        name: 'Zenith Apparel',
        taxId: '990-011-2233',
        email: 'hello@zenithapparel.com',
        phoneNumber: '+1-555-777-8888',
        address: '505 Fashion Blvd, Style City, CA 90012',
        detail: 'Fashion brand offering high-quality, contemporary clothing for all.',
        themeColor: 'turquoise',
    },
];
