import { userId, clientId } from '../ids';

export const panyaDesignWorkContacts = [
    {
        name: 'Nina Johnson',
        role: 'Project Manager',
        phoneNumber: '+66 88 123 4567',
        email: 'nina.johnson@email.com',
        details: 'Oversees design projects, ensures deadlines are met.',
        avatar: 'https://randomuser.me/api/portraits/women/45.jpg',
        userId: userId,
        companyId: clientId['Panya Design Works'],
    },
    {
        name: 'Kittisak Prakob',
        role: 'Creative Director',
        phoneNumber: '+66 92 234 5678',
        email: 'kittisak.prakob@email.com',
        details: 'Leads creative teams, develops visual concepts.',
        avatar: 'https://randomuser.me/api/portraits/men/34.jpg',
        userId: userId,
        companyId: clientId['Panya Design Works'],
    },
    {
        name: 'Sophie Williams',
        role: 'Marketing Lead',
        phoneNumber: '+66 93 345 6789',
        email: 'sophie.williams@email.com',
        details: 'Coordinates marketing campaigns and branding strategies.',
        avatar: 'https://randomuser.me/api/portraits/women/18.jpg',
        userId: userId,
        companyId: clientId['Panya Design Works'],
    },
    {
        name: 'Chanin Suphan',
        role: 'Content Strategist',
        phoneNumber: '+66 95 456 7890',
        email: 'chanin.suphan@email.com',
        details: 'Plans content strategy, writes copy for marketing.',
        avatar: 'https://randomuser.me/api/portraits/men/28.jpg',
        userId: userId,
        companyId: clientId['Panya Design Works'],
    },
    {
        name: 'Emma Green',
        role: 'Art Director',
        phoneNumber: '+66 87 567 8901',
        email: 'emma.green@email.com',
        details: 'Manages design aesthetics and visual style.',
        avatar: 'https://randomuser.me/api/portraits/women/60.jpg',
        userId: userId,
        companyId: clientId['Panya Design Works'],
    },
];

export const lotusRiversHotelContacts = [
    {
        name: 'James Clark',
        role: 'Marketing Manager',
        phoneNumber: '+66 81 234 5678',
        email: 'james.clark@lotusriverhotel.com',
        details: 'Leads marketing efforts, manages promotions and events.',
        avatar: 'https://randomuser.me/api/portraits/men/55.jpg',
        userId: userId,
        companyId: clientId['Lotus River Hotel'],
    },
    {
        name: 'Pimchanok Ratanapong',
        role: 'Public Relations Officer',
        phoneNumber: '+66 89 345 6789',
        email: 'pimchanok.ratanapong@lotusriverhotel.com',
        details: 'Handles media relations, coordinates PR campaigns.',
        avatar: 'https://randomuser.me/api/portraits/women/52.jpg',
        userId: userId,
        companyId: clientId['Lotus River Hotel'],
    },
    {
        name: 'Oliver Brown',
        role: 'Event Coordinator',
        phoneNumber: '+66 90 456 7890',
        email: 'oliver.brown@lotusriverhotel.com',
        details: 'Organizes events, liaises with external vendors.',
        avatar: 'https://randomuser.me/api/portraits/men/43.jpg',
        userId: userId,
        companyId: clientId['Lotus River Hotel'],
    },
    {
        name: 'Natthawan Kaewphong',
        role: 'Guest Relations Manager',
        phoneNumber: '+66 96 567 8901',
        email: 'natthawan.kaewphong@lotusriverhotel.com',
        details: 'Ensures guest satisfaction, oversees customer service.',
        avatar: 'https://randomuser.me/api/portraits/men/21.jpg',
        userId: userId,
        companyId: clientId['Lotus River Hotel'],
    },
    {
        name: 'Lily Turner',
        role: 'Branding Specialist',
        phoneNumber: '+66 85 678 9012',
        email: 'lily.turner@lotusriverhotel.com',
        details: 'Works on branding, advertising, and visual identity.',
        avatar: 'https://randomuser.me/api/portraits/women/61.jpg',
        userId: userId,
        companyId: clientId['Lotus River Hotel'],
    },
];

export const lannaAssociatesContacts = [
    {
        name: 'Lucas Brown',
        role: 'Brand Manager',
        phoneNumber: '+66 81 123 4567',
        email: 'lucas.brown@lanna.com',
        details: 'Leads brand development and market positioning.',
        avatar: 'https://randomuser.me/api/portraits/men/50.jpg',
        userId: userId,
        companyId: clientId['Lanna Associates'],
    },
    {
        name: 'Pimchanok Srisawat',
        role: 'Digital Marketing Specialist',
        phoneNumber: '+66 82 234 5678',
        email: 'pimchanok.srisawat@lanna.com',
        details: 'Oversees digital campaigns and social media strategies.',
        avatar: 'https://randomuser.me/api/portraits/women/55.jpg',
        userId: userId,
        companyId: clientId['Lanna Associates'],
    },
    {
        name: 'James Harris',
        role: 'Public Relations Manager',
        phoneNumber: '+66 90 345 6789',
        email: 'james.harris@lanna.com',
        details: 'Manages media relations and public image.',
        avatar: 'https://randomuser.me/api/portraits/men/26.jpg',
        userId: userId,
        companyId: clientId['Lanna Associates'],
    },
    {
        name: 'Suda Chanthapong',
        role: 'Marketing Coordinator',
        phoneNumber: '+66 89 456 7890',
        email: 'suda.chanthapong@lanna.com',
        details: 'Coordinates marketing efforts and event planning.',
        avatar: 'https://randomuser.me/api/portraits/women/46.jpg',
        userId: userId,
        companyId: clientId['Lanna Associates'],
    },
    {
        name: 'Ethan Parker',
        role: 'Advertising Strategist',
        phoneNumber: '+66 96 567 8901',
        email: 'ethan.parker@lanna.com',
        details: 'Develops advertising strategies and creative content.',
        avatar: 'https://randomuser.me/api/portraits/men/63.jpg',
        userId: userId,
        companyId: clientId['Lanna Associates'],
    },
];

export const sullivanPhanichContacts = [
    {
        name: 'James Sullivan',
        role: 'Marketing Manager',
        phoneNumber: '+66 81 234 5678',
        email: 'james.sullivan@sullivanphanich.com',
        details: 'Oversees marketing campaigns and external communications.',
        avatar: 'https://randomuser.me/api/portraits/men/52.jpg',
        userId: userId,
        companyId: clientId['Sullivan & Phanich'],
    },
    {
        name: 'Alicia Phanich',
        role: 'PR Specialist',
        phoneNumber: '+66 82 345 6789',
        email: 'alicia.phanich@sullivanphanich.com',
        details: 'Handles public relations, media outreach, and branding.',
        avatar: 'https://randomuser.me/api/portraits/women/32.jpg',
        userId: userId,
        companyId: clientId['Sullivan & Phanich'],
    },
    {
        name: 'Markus Lee',
        role: 'Client Relations Manager',
        phoneNumber: '+66 83 456 7890',
        email: 'markus.lee@sullivanphanich.com',
        details:
            'Manages client relationships and ensures client satisfaction.',
        avatar: 'https://randomuser.me/api/portraits/men/63.jpg',
        userId: userId,
        companyId: clientId['Sullivan & Phanich'],
    },
    {
        name: 'Siriwat Charoen',
        role: 'Digital Marketing Strategist',
        phoneNumber: '+66 95 567 8901',
        email: 'siriwat.charoen@sullivanphanich.com',
        details: 'Develops and executes digital marketing strategies.',
        avatar: 'https://randomuser.me/api/portraits/men/22.jpg',
        userId: userId,
        companyId: clientId['Sullivan & Phanich'],
    },
    {
        name: 'Isabella Turner',
        role: 'Content Manager',
        phoneNumber: '+66 94 678 9012',
        email: 'isabella.turner@sullivanphanich.com',
        details:
            'Manages content creation for marketing and external platforms.',
        avatar: 'https://randomuser.me/api/portraits/women/49.jpg',
        userId: userId,
        companyId: clientId['Sullivan & Phanich'],
    },
];

export const chaoprayaBankContact = [
    {
        name: 'Pattaraporn Chaiyawat',
        role: 'Marketing Manager',
        phoneNumber: '+66 89 123 4567',
        email: 'pattaraporn.chaiyawat@cpbank.com',
        details: 'Manages marketing campaigns and brand strategies.',
        avatar: 'https://randomuser.me/api/portraits/women/22.jpg',
        userId: userId,
        companyId: clientId['Chao Phraya Bank'],
    },
    {
        name: 'John Thompson',
        role: 'Digital Marketing Lead',
        phoneNumber: '+66 90 234 5678',
        email: 'john.thompson@cpbank.com',
        details: 'Leads digital campaigns and online brand presence.',
        avatar: 'https://randomuser.me/api/portraits/men/55.jpg',
        userId: userId,
        companyId: clientId['Chao Phraya Bank'],
    },
    {
        name: 'Nattapong Sakul',
        role: 'Product Marketing Specialist',
        phoneNumber: '+66 92 345 6789',
        email: 'nattapong.sakul@cpbank.com',
        details: 'Handles product-specific marketing materials and strategies.',
        avatar: 'https://randomuser.me/api/portraits/men/46.jpg',
        userId: userId,
        companyId: clientId['Chao Phraya Bank'],
    },
    {
        name: 'Sophia Li',
        role: 'Branding Consultant',
        phoneNumber: '+66 81 456 7890',
        email: 'sophia.li@cpbank.com',
        details: 'Works on refining the brand image and visual identity.',
        avatar: 'https://randomuser.me/api/portraits/women/58.jpg',
        userId: userId,
        companyId: clientId['Chao Phraya Bank'],
    },
    {
        name: 'Pachara Yuthapong',
        role: 'Public Relations Officer',
        phoneNumber: '+66 93 567 8901',
        email: 'pachara.yuthapong@cpbank.com',
        details: 'Manages public relations and media outreach.',
        avatar: 'https://randomuser.me/api/portraits/men/72.jpg',
        userId: userId,
        companyId: clientId['Chao Phraya Bank'],
    },
];

export const bambooBayBeautyContacts = [
    {
        name: 'Lena Richardson',
        role: 'Marketing Manager',
        phoneNumber: '+66 81 234 5678',
        email: 'lena.richardson@bamboobaybeauty.com',
        details: 'Leads marketing campaigns, works on branding initiatives.',
        avatar: 'https://randomuser.me/api/portraits/women/25.jpg',
        userId: userId,
        companyId: clientId['Bamboo Bay Beauty'],
    },
    {
        name: 'Natcha Somboon',
        role: 'Brand Strategist',
        phoneNumber: '+66 84 345 6789',
        email: 'natcha.somboon@bamboobaybeauty.com',
        details: 'Develops brand strategies and ensures visual consistency.',
        avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
        userId: userId,
        companyId: clientId['Bamboo Bay Beauty'],
    },
    {
        name: 'Oliver Hayes',
        role: 'Digital Marketing Specialist',
        phoneNumber: '+66 89 456 7890',
        email: 'oliver.hayes@bamboobaybeauty.com',
        details: 'Handles online campaigns, social media, and digital ads.',
        avatar: 'https://randomuser.me/api/portraits/men/16.jpg',
        userId: userId,
        companyId: clientId['Bamboo Bay Beauty'],
    },
    {
        name: 'Pailin Jantawong',
        role: 'Creative Lead',
        phoneNumber: '+66 82 567 8901',
        email: 'pailin.jantawong@bamboobaybeauty.com',
        details: 'Oversees creative projects and leads visual design work.',
        avatar: 'https://randomuser.me/api/portraits/women/22.jpg',
        userId: userId,
        companyId: clientId['Bamboo Bay Beauty'],
    },
    {
        name: 'Maxwell Black',
        role: 'Public Relations Officer',
        phoneNumber: '+66 83 678 9012',
        email: 'maxwell.black@bamboobaybeauty.com',
        details: 'Manages media relationships and press outreach.',
        avatar: 'https://randomuser.me/api/portraits/men/28.jpg',
        userId: userId,
        companyId: clientId['Bamboo Bay Beauty'],
    },
];

export const seedClientContactsData = [
    ...panyaDesignWorkContacts,
    ...lotusRiversHotelContacts,
    ...lannaAssociatesContacts,
    ...sullivanPhanichContacts,
    ...chaoprayaBankContact,
    ...bambooBayBeautyContacts,
];
