import { userId, clientId } from '../ids';

export const panyaDesignWorkProjects = [
    {
        title: 'Brand Identity for Thai Coffee Co.',
        budget: 50000,
        projectStatus: 'active',
        paymentStatus: 'unpaid',
        links: [
            'https://www.thai-coffee.com',
            'https://www.behance.net/brandidentity',
        ],
        note: 'Working on a complete rebrand, including logo, packaging, and website.',
        userId: userId,
        clientId: clientId['Panya Design Works'],
        pinned: true,
    },
    {
        title: 'Website Redesign for Siam Fashion',
        budget: 120000,
        projectStatus: 'on-hold',
        paymentStatus: 'processing',
        links: [
            'https://www.siamfashion.com',
            'https://www.behance.net/webdesign',
        ],
        note: 'Waiting for client approval on the final mockups before starting development.',
        userId: userId,
        clientId: clientId['Panya Design Works'],
        pinned: false,
    },
    {
        title: 'E-commerce Website for Thai Art Gallery',
        budget: 85000,
        projectStatus: 'active',
        paymentStatus: 'paid',
        links: [
            'https://www.thaiartgallery.com',
            'https://www.behance.net/artwebsite',
        ],
        note: 'Site completed with integrated online store and payment gateway.',
        userId: userId,
        pinned: false,
        clientId: clientId['Panya Design Works'],
    },
    {
        title: 'Social Media Campaign for Organic Farm',
        budget: 30000,
        projectStatus: 'completed',
        paymentStatus: 'paid',
        links: [
            'https://www.organicfarm.com',
            'https://www.behance.net/socialmedia',
        ],
        note: 'Full social media package delivered, including content and design.',
        userId: userId,
        pinned: true,
        clientId: clientId['Panya Design Works'],
    },
    {
        title: 'Packaging Design for Thai Tea Brand',
        budget: 45000,
        projectStatus: 'active',
        paymentStatus: 'processing',
        links: [
            'https://www.thaitea.com',
            'https://www.behance.net/packagingdesign',
        ],
        note: 'Designing packaging for a new range of products.',
        userId: userId,
        pinned: false,
        clientId: clientId['Panya Design Works'],
    },
    {
        title: 'Annual Report for Green Energy Corp.',
        budget: 70000,
        projectStatus: 'on-hold',
        paymentStatus: 'unpaid',
        links: [
            'https://www.greenenergy.com',
            'https://www.behance.net/reportdesign',
        ],
        note: 'Waiting for final data before proceeding with design.',
        userId: userId,
        pinned: false,
        clientId: clientId['Panya Design Works'],
    },
];

export const lotusRiverHotelProject = [
    {
        title: 'Website Redesign for Hotel Booking System',
        budget: 60000,
        projectStatus: 'active',
        paymentStatus: 'unpaid',
        links: [
            'https://www.lotusriverhotel.com',
            'https://www.behance.net/webdesign',
        ],
        note: 'Redesigning the hotel booking interface and improving mobile responsiveness.',
        userId: userId,
        pinned: true,
        clientId: clientId['Lotus River Hotel'],
    },
    {
        title: 'Brand Identity for New Luxury Suite',
        budget: 100000,
        projectStatus: 'on-hold',
        paymentStatus: 'processing',
        links: [
            'https://www.lotusriverhotel.com',
            'https://www.behance.net/branding',
        ],
        note: 'Designing a luxury suite brand identity including logo, brochures, and website.',
        userId: userId,
        pinned: false,
        clientId: clientId['Lotus River Hotel'],
    },
    {
        title: 'E-commerce Integration for Room Packages',
        budget: 75000,
        projectStatus: 'active',
        paymentStatus: 'paid',
        links: [
            'https://www.lotusriverhotel.com',
            'https://www.behance.net/ecommerce',
        ],
        note: 'Integrating room packages into an online store for easy booking.',
        userId: userId,
        pinned: false,
        clientId: clientId['Lotus River Hotel'],
    },
    {
        title: 'Social Media Campaign for Seasonal Promotions',
        budget: 25000,
        projectStatus: 'completed',
        paymentStatus: 'paid',
        links: [
            'https://www.lotusriverhotel.com',
            'https://www.behance.net/socialmedia',
        ],
        note: 'Creating promotional social media posts and ads for peak season discounts.',
        userId: userId,
        pinned: true,
        clientId: clientId['Lotus River Hotel'],
    },
    {
        title: 'Interior Design Concept for New Lobby',
        budget: 90000,
        projectStatus: 'active',
        paymentStatus: 'processing',
        links: [
            'https://www.lotusriverhotel.com',
            'https://www.behance.net/interiordesign',
        ],
        note: 'Designing the interior layout and decoration for a modern hotel lobby.',
        userId: userId,
        pinned: false,
        clientId: clientId['Lotus River Hotel'],
    },
    {
        title: 'Annual Report Design for Hotel Performance',
        budget: 50000,
        projectStatus: 'on-hold',
        paymentStatus: 'unpaid',
        links: [
            'https://www.lotusriverhotel.com',
            'https://www.behance.net/reportdesign',
        ],
        note: 'Creating an annual report highlighting the hotel’s yearly performance and achievements.',
        userId: userId,
        pinned: false,
        clientId: clientId['Lotus River Hotel'],
    },
];

export const lannaAssociatesProjects = [
    {
        title: 'Corporate Branding for New Subsidiary',
        budget: 120000,
        projectStatus: 'active',
        paymentStatus: 'unpaid',
        links: [
            'https://www.lannaassociates.com',
            'https://www.behance.net/branding',
        ],
        note: 'Developing brand identity for a newly acquired subsidiary, including logo, brand guidelines, and collateral.',
        userId: userId,
        clientId: clientId['Lanna Associates'],
        pinned: true,
    },
    {
        title: 'Investor Presentation Design for Quarterly Report',
        budget: 40000,
        projectStatus: 'completed',
        paymentStatus: 'paid',
        links: [
            'https://www.lannaassociates.com',
            'https://www.behance.net/presentationdesign',
        ],
        note: 'Designing a visually appealing investor presentation for quarterly earnings call.',
        userId: userId,
        clientId: clientId['Lanna Associates'],
        pinned: false,
    },
    {
        title: 'Market Research Infographics for New Product Launch',
        budget: 70000,
        projectStatus: 'active',
        paymentStatus: 'processing',
        links: [
            'https://www.lannaassociates.com',
            'https://www.behance.net/infographics',
        ],
        note: 'Creating a set of infographics to present market research data for a new product launch.',
        userId: userId,
        clientId: clientId['Lanna Associates'],
        pinned: false,
    },
    {
        title: 'Packaging Design for Consumer Electronics Line',
        budget: 90000,
        projectStatus: 'on-hold',
        paymentStatus: 'unpaid',
        links: [
            'https://www.lannaassociates.com',
            'https://www.behance.net/packagingdesign',
        ],
        note: 'Designing product packaging for a new consumer electronics line under one of the subsidiaries.',
        userId: userId,
        clientId: clientId['Lanna Associates'],
        pinned: true,
    },
    {
        title: 'Corporate Event Branding for Annual Conference',
        budget: 60000,
        projectStatus: 'active',
        paymentStatus: 'paid',
        links: [
            'https://www.lannaassociates.com',
            'https://www.behance.net/eventbranding',
        ],
        note: 'Creating event branding for the company’s annual conference, including signage, banners, and presentation decks.',
        userId: userId,
        clientId: clientId['Lanna Associates'],
        pinned: false,
    },
    {
        title: 'Advertising Campaign for New Retail Product Line',
        budget: 110000,
        projectStatus: 'completed',
        paymentStatus: 'paid',
        links: [
            'https://www.lannaassociates.com',
            'https://www.behance.net/advertising',
        ],
        note: 'Designing an advertising campaign for the new retail product line, including print, digital, and TV ads.',
        userId: userId,
        clientId: clientId['Lanna Associates'],
        pinned: false,
    },
];

export const sullivanPhanichProjects = [
    {
        title: 'Brand Identity Redesign for Law Firm',
        budget: 80000,
        projectStatus: 'active',
        paymentStatus: 'unpaid',
        links: [
            'https://www.sullivanphanich.com',
            'https://www.behance.net/branding',
        ],
        note: 'Redesigning the law firm’s branding, including logo, business cards, and letterhead.',
        userId: userId,
        clientId: clientId['Sullivan & Phanich'],
        pinned: true,
    },
    {
        title: 'Legal Document Templates for Corporate Clients',
        budget: 45000,
        projectStatus: 'completed',
        paymentStatus: 'paid',
        links: [
            'https://www.sullivanphanich.com',
            'https://www.behance.net/documentdesign',
        ],
        note: 'Creating a set of customizable legal document templates for the firm’s corporate clients.',
        userId: userId,
        clientId: clientId['Sullivan & Phanich'],
        pinned: false,
    },
    {
        title: 'Client Onboarding Guide Design',
        budget: 35000,
        projectStatus: 'active',
        paymentStatus: 'processing',
        links: [
            'https://www.sullivanphanich.com',
            'https://www.behance.net/guidebook',
        ],
        note: 'Designing a client onboarding guide for new legal clients, including a step-by-step process and relevant forms.',
        userId: userId,
        clientId: clientId['Sullivan & Phanich'],
        pinned: false,
    },
    {
        title: 'Brochure Design for Family Law Services',
        budget: 25000,
        projectStatus: 'completed',
        paymentStatus: 'paid',
        links: [
            'https://www.sullivanphanich.com',
            'https://www.behance.net/brochure',
        ],
        note: 'Designing an informative brochure to promote family law services offered by the firm.',
        userId: userId,
        clientId: clientId['Sullivan & Phanich'],
        pinned: true,
    },
    {
        title: 'Annual Legal Insights Report Design',
        budget: 70000,
        projectStatus: 'on-hold',
        paymentStatus: 'unpaid',
        links: [
            'https://www.sullivanphanich.com',
            'https://www.behance.net/reportdesign',
        ],
        note: 'Designing the layout and graphics for the firm’s annual report highlighting legal insights and case studies.',
        userId: userId,
        clientId: clientId['Sullivan & Phanich'],
        pinned: false,
    },
    {
        title: 'Ad Campaign for Personal Injury Law Services',
        budget: 95000,
        projectStatus: 'active',
        paymentStatus: 'processing',
        links: [
            'https://www.sullivanphanich.com',
            'https://www.behance.net/adcampaign',
        ],
        note: 'Creating a targeted advertising campaign to promote the firm’s personal injury law services across digital and print media.',
        userId: userId,
        clientId: clientId['Sullivan & Phanich'],
        pinned: false,
    },
];

export const chaoprayaBankProjects = [
    {
        title: 'Customer Service Training Manual',
        budget: 60000,
        projectStatus: 'active',
        paymentStatus: 'unpaid',
        links: [
            'https://www.chaophrayabank.com',
            'https://www.behance.net/training',
        ],
        note: 'Designing a comprehensive customer service training manual for the bank’s front-line staff.',
        userId: userId,
        clientId: clientId['Chao Phraya Bank'],
        pinned: true,
    },
    {
        title: 'Mobile App User Interface Improvements',
        budget: 90000,
        projectStatus: 'on-hold',
        paymentStatus: 'processing',
        links: [
            'https://www.chaophrayabank.com',
            'https://www.behance.net/appdesign',
        ],
        note: "Making improvements to the user interface of the bank's mobile app for a better customer experience.",
        userId: userId,
        clientId: clientId['Chao Phraya Bank'],
        pinned: false,
    },
    {
        title: 'In-Branch Signage System',
        budget: 45000,
        projectStatus: 'completed',
        paymentStatus: 'paid',
        links: [
            'https://www.chaophrayabank.com',
            'https://www.behance.net/signage',
        ],
        note: 'Designing an updated signage system for branches, including directional signs and service information.',
        userId: userId,
        clientId: clientId['Chao Phraya Bank'],
        pinned: false,
    },
    {
        title: 'Customer Feedback Survey Layout',
        budget: 25000,
        projectStatus: 'active',
        paymentStatus: 'unpaid',
        links: [
            'https://www.chaophrayabank.com',
            'https://www.behance.net/surveydesign',
        ],
        note: 'Designing a customer feedback survey to gather insights about services provided by the bank.',
        userId: userId,
        clientId: clientId['Chao Phraya Bank'],
        pinned: true,
    },
    {
        title: 'New Loan Product Information Brochure',
        budget: 70000,
        projectStatus: 'completed',
        paymentStatus: 'paid',
        links: [
            'https://www.chaophrayabank.com',
            'https://www.behance.net/brochure',
        ],
        note: 'Creating a detailed brochure for a new loan product, outlining terms, benefits, and application process.',
        userId: userId,
        clientId: clientId['Chao Phraya Bank'],
        pinned: false,
    },
    {
        title: 'Training Video for Online Banking System',
        budget: 80000,
        projectStatus: 'active',
        paymentStatus: 'processing',
        links: [
            'https://www.chaophrayabank.com',
            'https://www.behance.net/video',
        ],
        note: 'Producing an instructional video to guide customers through the bank’s online banking system.',
        userId: userId,
        clientId: clientId['Chao Phraya Bank'],
        pinned: false,
    },
];

export const bambooBayBeautyProjects = [
    {
        title: 'Product Packaging Design for New Skincare Line',
        budget: 50000,
        projectStatus: 'active',
        paymentStatus: 'unpaid',
        links: [
            'https://www.bamboobaybeauty.com',
            'https://www.behance.net/packagingdesign',
        ],
        note: 'Designing the packaging for a new skincare product line, including labels and boxes.',
        userId: userId,
        clientId: clientId['Bamboo Bay Beauty'],
        pinned: true,
    },
    {
        title: 'Social Media Content Creation for Product Launch',
        budget: 25000,
        projectStatus: 'completed',
        paymentStatus: 'paid',
        links: [
            'https://www.bamboobaybeauty.com',
            'https://www.behance.net/socialmediacontent',
        ],
        note: 'Creating visually appealing content for social media platforms to launch a new skincare product.',
        userId: userId,
        clientId: clientId['Bamboo Bay Beauty'],
        pinned: false,
    },
    {
        title: 'Skincare Blog Design for Company Website',
        budget: 40000,
        projectStatus: 'active',
        paymentStatus: 'processing',
        links: [
            'https://www.bamboobaybeauty.com',
            'https://www.behance.net/webdesign',
        ],
        note: 'Designing a blog section for the website to share skincare tips, customer testimonials, and product news.',
        userId: userId,
        clientId: clientId['Bamboo Bay Beauty'],
        pinned: false,
    },
    {
        title: 'Email Newsletter Template Design',
        budget: 15000,
        projectStatus: 'completed',
        paymentStatus: 'paid',
        links: [
            'https://www.bamboobaybeauty.com',
            'https://www.behance.net/emaildesign',
        ],
        note: 'Designing a series of email templates for marketing campaigns, product launches, and promotions.',
        userId: userId,
        clientId: clientId['Bamboo Bay Beauty'],
        pinned: true,
    },
    {
        title: 'Retail Display for In-Store Product Promotion',
        budget: 35000,
        projectStatus: 'on-hold',
        paymentStatus: 'unpaid',
        links: [
            'https://www.bamboobaybeauty.com',
            'https://www.behance.net/retaildesign',
        ],
        note: 'Designing an attractive retail display to showcase skincare products in partner stores.',
        userId: userId,
        clientId: clientId['Bamboo Bay Beauty'],
        pinned: false,
    },
    {
        title: 'Customer Testimonials Video for Skincare Products',
        budget: 60000,
        projectStatus: 'active',
        paymentStatus: 'processing',
        links: [
            'https://www.bamboobaybeauty.com',
            'https://www.behance.net/videocontent',
        ],
        note: 'Producing a series of customer testimonial videos to build trust and promote the brand.',
        userId: userId,
        clientId: clientId['Bamboo Bay Beauty'],
        pinned: false,
    },
];

export const seedProjectsData = [
    ...panyaDesignWorkProjects,
    ...lotusRiverHotelProject,
    ...lannaAssociatesProjects,
    ...sullivanPhanichProjects,
    ...chaoprayaBankProjects,
    ...bambooBayBeautyProjects,
];
