export const seedPartnerCompaniesData = [
    {
        name: 'Momentum Studios',
        taxId: '0105581123457',
        email: 'contact@momentumstudios.com',
        phoneNumber: '+66 2 134 5678',
        address: '123 Sukhumvit Rd, Khlong Tan, Bangkok 10110, Thailand',
        detail: 'Creative production studio specializing in high-impact advertising campaigns and branded content.',
    },
    {
        name: 'Visionary Talent Agency',
        taxId: '0105528123451',
        email: 'info@visionarytalent.com',
        phoneNumber: '+66 2 456 7890',
        address: '45 Silom Rd, Bang Rak, Bangkok 10500, Thailand',
        detail: 'Talent agency representing leading actors, influencers, and models for advertising and media campaigns.',
    },
    {
        name: 'Echo Media Group',
        taxId: '0105566129870',
        email: 'hello@echomediagroup.com',
        phoneNumber: '+66 99 234 5678',
        address: '678 Rama 9 Rd, Huai Khwang, Bangkok 10310, Thailand',
        detail: 'Advertising agency focused on digital marketing and experiential brand activations.',
    },
    {
        name: 'Flicker Films',
        taxId: '0105592348779',
        email: 'contact@flickerfilms.com',
        phoneNumber: '+66 2 890 1234',
        address: '89 Asoke Rd, Khlong Toei, Bangkok 10110, Thailand',
        detail: 'Full-service production company specializing in film, video, and commercial production.',
    },
    {
        name: 'Pulse Creative',
        taxId: '0105538765432',
        email: 'support@pulsecreative.com',
        phoneNumber: '+66 2 678 9012',
        address: '123 Phetchaburi Rd, Makkasan, Bangkok 10400, Thailand',
        detail: 'Innovative creative agency specializing in advertising and branding for tech startups.',
    },
    {
        name: 'Zenith Talent',
        taxId: '0105578954321',
        email: 'info@zenithtalent.com',
        phoneNumber: '+66 2 564 9876',
        address: '456 Thonglor Rd, Watthana, Bangkok 10110, Thailand',
        detail: 'Talent agency connecting top influencers with global brands for marketing campaigns.',
    },
    {
        name: 'Freelancers',
        taxId: '',
        email: '',
        phoneNumber: '',
        address: '',
        detail: '',
    },
];
