import { getRandomFileSize, Ids } from '@/demo/helpers/seed-user-data/helper';

export const generateEcommercePlatformUiUxRedesignFiles = (ids: Ids) => {
    const projectKebabCase = 'e-commerce-platform-ui-ux-redesign';

    return [
        {
            originalName: 'ui_ux_redesign_brief_v1.pdf',
            name: 'UI/UX Redesign Project Brief',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/ui_ux_redesign_brief_v1.pdf`,
            size: getRandomFileSize(400, 800),
            ...ids,
        },
        {
            originalName: 'initial_wireframes_approved.fig',
            name: 'Initial Wireframes (Approved)',
            type: 'design',
            category: 'work',
            link: 'https://www.figma.com/file/bytenest_wireframes_approved',
            ...ids,
        },
        {
            originalName: 'high_fidelity_mockups_progress_june15.xd',
            name: 'High-Fidelity Mockups (WIP)',
            type: 'design',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/high_fidelity_mockups_progress_june15.xd`,
            size: getRandomFileSize(15000, 30000),
            ...ids,
        },
        {
            originalName: 'navigation_motion_prototypes_v1.mp4',
            name: 'Navigation Motion Prototypes',
            type: 'video',
            category: 'work',
            link: 'https://vimeo.com/bytenest_motion_prototypes_v1',
            ...ids,
        },
        {
            originalName: 'competitor_ui_trends_shopflow.pdf',
            name: 'Competitor UI Trends (ShopFlow)',
            type: 'document',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/competitor_ui_trends_shopflow.pdf`,
            size: getRandomFileSize(300, 600),
            ...ids,
        },
        {
            originalName: 'user_research_findings_summary.pdf',
            name: 'User Research Findings Summary',
            type: 'document',
            category: 'asset',
            link: 'https://docs.google.com/document/d/bytenest_user_research',
            ...ids,
        },
        {
            originalName: 'existing_ecom_platform_audit.xlsx',
            name: 'Existing Platform Audit',
            type: 'spreadsheet',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/existing_ecom_platform_audit.xlsx`,
            size: getRandomFileSize(200, 400),
            ...ids,
        },
        {
            originalName: 'brand_style_guide_bytenest.pdf',
            name: 'ByteNest Brand Style Guide',
            type: 'document',
            category: 'asset',
            link: 'https://example.com/bytenest_brand_guide.pdf',
            ...ids,
        },
        {
            originalName: 'client_brand_assets_ecommerce.zip',
            name: 'Client Brand Assets',
            type: 'archive',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/client_brand_assets_ecommerce.zip`,
            size: getRandomFileSize(10000, 25000),
            ...ids,
        },
        {
            originalName: 'sitemap_and_user_flows_v2.fig',
            name: 'Sitemap & User Flows',
            type: 'design',
            category: 'asset',
            link: 'https://www.figma.com/file/bytenest_sitemap_userflows',
            ...ids,
        },
        {
            originalName: 'accessibility_checklist.pdf',
            name: 'Accessibility Checklist',
            type: 'document',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/accessibility_checklist.pdf`,
            size: getRandomFileSize(100, 200),
            ...ids,
        },
    ];
};

export const generateInternalCrmSystemApiIntegrationFiles = (ids: Ids) => {
    const projectKebabCase = 'internal-crm-system-api-integration';

    return [
        {
            originalName: 'api_integration_project_plan_v1.pdf',
            name: 'API Integration Project Plan',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/api_integration_project_plan_v1.pdf`,
            size: getRandomFileSize(300, 600),
            ...ids,
        },
        {
            originalName: 'authentication_method_proposal.docx',
            name: 'Authentication Method Proposal',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/authentication_method_proposal.docx`,
            size: getRandomFileSize(100, 200),
            ...ids,
        },
        {
            originalName: 'integration_test_cases_suite_1.xlsx',
            name: 'Integration Test Cases (Suite 1)',
            type: 'spreadsheet',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/integration_test_cases_suite_1.xlsx`,
            size: getRandomFileSize(150, 300),
            ...ids,
        },
        {
            originalName: 'development_roadmap_api_integration.pptx',
            name: 'API Integration Development Roadmap',
            type: 'presentation',
            category: 'work',
            link: 'https://docs.google.com/presentation/d/bytenest_crm_api_roadmap',
            ...ids,
        },
        {
            originalName: 'security_audit_report_draft.pdf',
            name: 'Security Audit Report Draft',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/security_audit_report_draft.pdf`,
            size: getRandomFileSize(400, 700),
            ...ids,
        },
        {
            originalName: 'deployment_checklist_v1.docx',
            name: 'Deployment Checklist',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/deployment_checklist_v1.docx`,
            size: getRandomFileSize(80, 150),
            ...ids,
        },
        {
            originalName: 'api_integration_code_base_v1.zip',
            name: 'API Integration Codebase (v1)',
            type: 'code',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/api_integration_code_base_v1.zip`,
            size: getRandomFileSize(5000, 10000),
            ...ids,
        },
        {
            originalName: 'user_acceptance_testing_results.pdf',
            name: 'User Acceptance Testing Results',
            type: 'document',
            category: 'work',
            link: 'https://example.com/bytenest_uat_results.pdf',
            ...ids,
        },
        {
            originalName: 'performance_testing_summary.pdf',
            name: 'Performance Testing Summary',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/performance_testing_summary.pdf`,
            size: getRandomFileSize(200, 400),
            ...ids,
        },
        {
            originalName: 'crm_api_documentation_external.pdf',
            name: 'CRM API Documentation',
            type: 'document',
            category: 'asset',
            link: 'https://developer.bytenestcrm.com/api-docs',
            ...ids,
        },
        {
            originalName: 'bytenest_network_architecture.vsdx',
            name: 'ByteNest Network Architecture Diagram',
            type: 'design',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/bytenest_network_architecture.vsdx`,
            size: getRandomFileSize(700, 1200),
            ...ids,
        },
        {
            originalName: 'existing_crm_data_schema.sql',
            name: 'Existing CRM Data Schema',
            type: 'database',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/existing_crm_data_schema.sql`,
            size: getRandomFileSize(50, 100),
            ...ids,
        },
        {
            originalName: 'api_security_best_practices.pdf',
            name: 'API Security Best Practices Guide',
            type: 'document',
            category: 'asset',
            link: 'https://owasp.org/www-project-api-security',
            ...ids,
        },
        {
            originalName: 'internal_team_contact_list.xlsx',
            name: 'Internal Development Team Contacts',
            type: 'spreadsheet',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/internal_team_contact_list.xlsx`,
            size: getRandomFileSize(30, 60),
            ...ids,
        },
        {
            originalName: 'api_key_management_policy.pdf',
            name: 'API Key Management Policy',
            type: 'document',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/api_key_management_policy.pdf`,
            size: getRandomFileSize(120, 250),
            ...ids,
        },
        {
            originalName: 'jira_project_board_link.url',
            name: 'Jira Project Board',
            type: 'project-management',
            category: 'asset',
            link: 'https://bytenest.atlassian.net/jira/software/projects/CRMINTEG/board',
            ...ids,
        },
    ];
};

export const generateProductLaunchVideoAndExplainerAnimationFiles = (
    ids: Ids,
) => {
    const projectKebabCase = 'product-launch-video-explainer-animation';

    return [
        {
            originalName: 'video_project_brief_bytenest.pdf',
            name: 'Product Launch Video Brief',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/video_project_brief_bytenest.pdf`,
            size: getRandomFileSize(400, 700),
            ...ids,
        },
        {
            originalName: 'script_draft_explainer_animation_v2.docx',
            name: 'Explainer Animation Script Draft',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/script_draft_explainer_animation_v2.docx`,
            size: getRandomFileSize(100, 200),
            ...ids,
        },
        {
            originalName: 'storyboard_product_launch_video.pdf',
            name: 'Product Launch Video Storyboard',
            type: 'design',
            category: 'work',
            link: 'https://www.figma.com/file/bytenest_video_storyboard',
            ...ids,
        },
        {
            originalName: 'animation_style_guide.pdf',
            name: 'Explainer Animation Style Guide',
            type: 'design',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/animation_style_guide.pdf`,
            size: getRandomFileSize(600, 1000),
            ...ids,
        },
        {
            originalName: 'voice_over_recording_script_final.docx',
            name: 'Voice-Over Recording Script (Final)',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/voice_over_recording_script_final.docx`,
            size: getRandomFileSize(50, 100),
            ...ids,
        },
        {
            originalName: 'initial_video_edit_cut_v1.mp4',
            name: 'Initial Video Edit (Cut 1)',
            type: 'video',
            category: 'work',
            link: 'https://vimeo.com/bytenest_product_launch_v1_review',
            ...ids,
        },
        {
            originalName: 'client_feedback_form_video.xlsx',
            name: 'Client Feedback Form',
            type: 'spreadsheet',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/client_feedback_form_video.xlsx`,
            size: getRandomFileSize(70, 140),
            ...ids,
        },
        {
            originalName: 'project_hold_notification_email.pdf',
            name: 'Project On-Hold Notification',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/project_hold_notification_email.pdf`,
            size: getRandomFileSize(50, 100),
            ...ids,
        },
        {
            originalName: 'q4_2025_restart_timeline_draft.pptx',
            name: 'Q4 2025 Restart Timeline Draft',
            type: 'presentation',
            category: 'work',
            link: 'https://docs.google.com/presentation/d/bytenest_q4_restart_plan',
            ...ids,
        },
        {
            originalName: 'bytenest_product_specs_sheet.pdf',
            name: 'ByteNest Product Specifications',
            type: 'document',
            category: 'asset',
            link: 'https://example.com/bytenest_product_specs.pdf',
            ...ids,
        },
        {
            originalName: 'brand_logo_assets.ai',
            name: 'Brand Logo Assets',
            type: 'design',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/brand_logo_assets.ai`,
            size: getRandomFileSize(300, 600),
            ...ids,
        },
        {
            originalName: 'stock_footage_library_access.txt',
            name: 'Stock Footage Library Access',
            type: 'other',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/stock_footage_library_access.txt`,
            size: getRandomFileSize(10, 30),
            ...ids,
        },
        {
            originalName: 'voice_over_artist_demos.zip',
            name: 'Voice-Over Artist Demos',
            type: 'audio',
            category: 'asset',
            link: 'https://soundcloud.com/bytenest_vo_demos',
            ...ids,
        },
        {
            originalName: 'background_music_licenses.xlsx',
            name: 'Background Music Licenses',
            type: 'spreadsheet',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/background_music_licenses.xlsx`,
            size: getRandomFileSize(80, 150),
            ...ids,
        },
        {
            originalName: 'mr_anan_bytenest_pm_contact.vcf',
            name: 'Mr. Anan (ByteNest PM) Contact',
            type: 'other',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/mr_anan_bytenest_pm_contact.vcf`,
            size: getRandomFileSize(5, 15),
            ...ids,
        },
        {
            originalName: 'marketing_channels_brief.pdf',
            name: 'Marketing Channels Brief',
            type: 'document',
            category: 'asset',
            link: 'https://example.com/bytenest_marketing_channels.pdf',
            ...ids,
        },
    ];
};

export const generateAutomatedDataReportingDashboardFiles = (ids: Ids) => {
    const projectKebabCase = 'automated-data-reporting-dashboard';

    return [
        {
            originalName: 'dashboard_requirements_spec_final.pdf',
            name: 'Dashboard Requirements Specification',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/dashboard_requirements_spec_final.pdf`,
            size: getRandomFileSize(500, 1000),
            ...ids,
        },
        {
            originalName: 'dashboard_ui_mockups_approved.fig',
            name: 'Dashboard UI Mockups (Approved)',
            type: 'design',
            category: 'work',
            link: 'https://www.figma.com/file/bytenest_dashboard_ui_approved',
            ...ids,
        },
        {
            originalName: 'backend_api_documentation_v3.pdf',
            name: 'Backend API Documentation',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/backend_api_documentation_v3.pdf`,
            size: getRandomFileSize(300, 600),
            ...ids,
        },
        {
            originalName: 'final_dashboard_access_link.url',
            name: 'Final Dashboard Access Link',
            type: 'other',
            category: 'work',
            link: 'https://dashboard.bytenesttech.com/reports/main',
            ...ids,
        },
        {
            originalName: 'training_session_materials_bytenest.pptx',
            name: 'Training Session Presentation',
            type: 'presentation',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/training_session_materials_bytenest.pptx`,
            size: getRandomFileSize(700, 1500),
            ...ids,
        },
        {
            originalName: 'project_sign_off_document_final.pdf',
            name: 'Project Sign-Off Document',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/project_sign_off_document_final.pdf`,
            size: getRandomFileSize(100, 200),
            ...ids,
        },
        {
            originalName: 'user_manual_dashboard_v1.pdf',
            name: 'Dashboard User Manual',
            type: 'document',
            category: 'work',
            link: 'https://docs.google.com/document/d/bytenest_dashboard_user_manual',
            ...ids,
        },
        {
            originalName: 'client_testimonial_request_template.docx',
            name: 'Client Testimonial Request',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/client_testimonial_request_template.docx`,
            size: getRandomFileSize(30, 70),
            ...ids,
        },
        {
            originalName: 'post_mortem_review_notes_bytenest.pdf',
            name: 'Post-Mortem Review Notes',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/post_mortem_review_notes_bytenest.pdf`,
            size: getRandomFileSize(200, 400),
            ...ids,
        },
        {
            originalName: 'data_source_connections_diagram.pdf',
            name: 'Data Source Connections Diagram',
            type: 'design',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/data_source_connections_diagram.pdf`,
            size: getRandomFileSize(400, 800),
            ...ids,
        },
        {
            originalName: 'bytenest_data_dictionary.xlsx',
            name: 'ByteNest Data Dictionary',
            type: 'spreadsheet',
            category: 'asset',
            link: 'https://docs.google.com/spreadsheets/d/bytenest_data_dictionary',
            ...ids,
        },
        {
            originalName: 'database_credentials_secure_vault.url',
            name: 'Database Credentials (Secure Vault)',
            type: 'other',
            category: 'asset',
            link: 'https://securevault.bytenesttech.com/credentials/dashboard_db',
            ...ids,
        },
        {
            originalName: 'existing_reporting_templates.zip',
            name: 'Existing Reporting Templates',
            type: 'archive',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/existing_reporting_templates.zip`,
            size: getRandomFileSize(5000, 10000),
            ...ids,
        },
        {
            originalName: 'power_bi_licensing_info.pdf',
            name: 'Power BI Licensing Information',
            type: 'document',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/power_bi_licensing_info.pdf`,
            size: getRandomFileSize(100, 200),
            ...ids,
        },
        {
            originalName: 'qa_testing_protocols.pdf',
            name: 'QA Testing Protocols',
            type: 'document',
            category: 'asset',
            link: 'https://example.com/bytenest_qa_protocols.pdf',
            ...ids,
        },
        {
            originalName: 'client_data_privacy_policy.pdf',
            name: 'Client Data Privacy Policy',
            type: 'document',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/client_data_privacy_policy.pdf`,
            size: getRandomFileSize(200, 400),
            ...ids,
        },
    ];
};

export const generateWebsitePerformanceAuditOptimizationFiles = (ids: Ids) => {
    const projectKebabCase = 'website-performance-audit-optimization';

    return [
        {
            originalName: 'initial_audit_report_draft.pdf',
            name: 'Initial Website Audit Report Draft',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/initial_audit_report_draft.pdf`,
            size: getRandomFileSize(700, 1500),
            ...ids,
        },
        {
            originalName: 'client_meeting_presentation_june17.pptx',
            name: 'Client Meeting Presentation (June 17)',
            type: 'presentation',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/client_meeting_presentation_june17.pptx`,
            size: getRandomFileSize(800, 1800),
            ...ids,
        },
        {
            originalName: 'optimization_recommendations_v1.docx',
            name: 'Optimization Recommendations (Draft)',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/optimization_recommendations_v1.docx`,
            size: getRandomFileSize(200, 400),
            ...ids,
        },
        {
            originalName: 'core_web_vitals_analysis.xlsx',
            name: 'Core Web Vitals Analysis Data',
            type: 'spreadsheet',
            category: 'work',
            link: 'https://docs.google.com/spreadsheets/d/bytenest_cwv_analysis',
            ...ids,
        },
        {
            originalName: 'server_response_time_metrics.pdf',
            name: 'Server Response Time Metrics',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/server_response_time_metrics.pdf`,
            size: getRandomFileSize(300, 600),
            ...ids,
        },
        {
            originalName: 'action_plan_prioritized_tasks.xlsx',
            name: 'Prioritized Optimization Action Plan',
            type: 'spreadsheet',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/action_plan_prioritized_tasks.xlsx`,
            size: getRandomFileSize(150, 300),
            ...ids,
        },
        {
            originalName: 'post_optimization_report_template.pdf',
            name: 'Post-Optimization Report Template',
            type: 'document',
            category: 'work',
            link: 'https://example.com/bytenest_post_opt_report_template.pdf',
            ...ids,
        },
        {
            originalName: 'website_crawl_data_snapshot.zip',
            name: 'Website Crawl Data Snapshot',
            type: 'archive',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/website_crawl_data_snapshot.zip`,
            size: getRandomFileSize(10000, 25000),
            ...ids,
        },
        {
            originalName: 'google_analytics_access_details.txt',
            name: 'Google Analytics Access Details',
            type: 'document',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/google_analytics_access_details.txt`,
            size: getRandomFileSize(10, 30),
            ...ids,
        },
        {
            originalName: 'gtmetrix_lighthouse_reports.zip',
            name: 'GTmetrix & Lighthouse Raw Reports',
            type: 'archive',
            category: 'asset',
            link: 'https://drive.google.com/drive/folders/bytenest_performance_reports',
            ...ids,
        },
        {
            originalName: 'bytenest_server_config.conf',
            name: 'ByteNest Server Configuration (Partial)',
            type: 'code',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/bytenest_server_config.conf`,
            size: getRandomFileSize(50, 100),
            ...ids,
        },
        {
            originalName: 'competitor_performance_benchmarks.xlsx',
            name: 'Competitor Performance Benchmarks',
            type: 'spreadsheet',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/competitor_performance_benchmarks.xlsx`,
            size: getRandomFileSize(100, 200),
            ...ids,
        },
        {
            originalName: 'cdn_integration_docs.pdf',
            name: 'CDN Integration Documentation',
            type: 'document',
            category: 'asset',
            link: 'https://example.com/cdn_provider_docs.pdf',
            ...ids,
        },
        {
            originalName: 'website_codebase_access_details.txt',
            name: 'Website Codebase Access Details',
            type: 'document',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/website_codebase_access_details.txt`,
            size: getRandomFileSize(20, 50),
            ...ids,
        },
        {
            originalName: 'image_optimization_tools_info.pdf',
            name: 'Image Optimization Tools Information',
            type: 'document',
            category: 'asset',
            link: 'https://example.com/image_optimization_tools_guide.pdf',
            ...ids,
        },
        {
            originalName: 'bytenest_marketing_goals_brief.pdf',
            name: 'ByteNest Marketing Goals Brief',
            type: 'document',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/bytenest_marketing_goals_brief.pdf`,
            size: getRandomFileSize(150, 300),
            ...ids,
        },
    ];
};

export const getByteNestTechSolutionsFiles = (ids: Ids) => {
    const byteNestTechSolutionsFileGenerators: [string, any][] = [
        [
            'E-commerce Platform UI/UX Redesign',
            generateEcommercePlatformUiUxRedesignFiles,
        ],
        [
            'Internal CRM System API Integration',
            generateInternalCrmSystemApiIntegrationFiles,
        ],
        [
            'Product Launch Video & Explainer Animation',
            generateProductLaunchVideoAndExplainerAnimationFiles,
        ],
        [
            'Automated Data Reporting Dashboard',
            generateAutomatedDataReportingDashboardFiles,
        ],
        [
            'Website Performance Audit & Optimization',
            generateWebsitePerformanceAuditOptimizationFiles,
        ],
    ];

    return byteNestTechSolutionsFileGenerators.flatMap(
        ([projectTitle, generateFn]) => {
            const projectIds = ids[projectTitle];

            if (!projectIds) {
                console.warn(
                    `Warning: IDs not found for project: "${projectTitle}" for ByteNest Tech Solutions. No files generated.`,
                );
                return [];
            }

            return generateFn(projectIds);
        },
    );
};
