import { getRandomFileSize, Ids } from '@/demo/helpers/seed-user-data/level-3';

export const generateSummerChallengeLandingPageAdCreativesFiles = (
    ids: Ids,
) => {
    const projectKebabCase = 'summer-challenge-landing-page-ad-creatives';

    return [
        {
            originalName: 'summer_challenge_brief_final.pdf',
            name: 'Summer Challenge Project Brief',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/summer_challenge_brief_final.pdf`,
            size: getRandomFileSize(300, 600),
            ...ids,
        },
        {
            originalName: 'landing_page_wireframes_v2.fig',
            name: 'Landing Page Wireframes',
            type: 'design',
            category: 'work',
            link: 'https://www.figma.com/file/urbanflow_summer_lp_wireframes',
            ...ids,
        },
        {
            originalName: 'ad_creatives_concepts_batch1.zip',
            name: 'Ad Creatives Concepts (Batch 1)',
            type: 'image',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/ad_creatives_concepts_batch1.zip`,
            size: getRandomFileSize(8000, 15000),
            ...ids,
        },
        {
            originalName: 'cta_performance_ab_test_plan.xlsx',
            name: 'CTA A/B Test Plan',
            type: 'spreadsheet',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/cta_performance_ab_test_plan.xlsx`,
            size: getRandomFileSize(100, 200),
            ...ids,
        },
        {
            originalName: 'headline_ab_testing_framework.pdf',
            name: 'Headline A/B Testing Framework',
            type: 'document',
            category: 'work',
            link: 'https://example.com/urbanflow_headline_ab_test_guide.pdf',
            ...ids,
        },
        {
            originalName: 'final_landing_page_content_copy.docx',
            name: 'Final Landing Page Content Copy',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/final_landing_page_content_copy.docx`,
            size: getRandomFileSize(50, 100),
            ...ids,
        },
        {
            originalName: 'social_media_ad_specs_urbanflow.pdf',
            name: 'Social Media Ad Specifications',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/social_media_ad_specs_urbanflow.pdf`,
            size: getRandomFileSize(120, 250),
            ...ids,
        },
        {
            originalName: 'urbanflow_brand_guidelines.pdf',
            name: 'UrbanFlow Brand Guidelines',
            type: 'document',
            category: 'asset',
            link: 'https://example.com/urbanflow_brand_guide.pdf',
            ...ids,
        },
        {
            originalName: 'stock_photo_library_access.txt',
            name: 'Stock Photo Library Access',
            type: 'other',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/stock_photo_library_access.txt`,
            size: getRandomFileSize(10, 30),
            ...ids,
        },
        {
            originalName: 'competitor_ad_analysis_report.pdf',
            name: 'Competitor Ad Analysis Report',
            type: 'document',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/competitor_ad_analysis_report.pdf`,
            size: getRandomFileSize(300, 600),
            ...ids,
        },
        {
            originalName: 'user_persona_profiles.pdf',
            name: 'User Persona Profiles',
            type: 'document',
            category: 'asset',
            link: 'https://docs.google.com/document/d/urbanflow_user_personas',
            ...ids,
        },
        {
            originalName: 'google_ads_account_details.txt',
            name: 'Google Ads Account Details',
            type: 'document',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/google_ads_account_details.txt`,
            size: getRandomFileSize(20, 50),
            ...ids,
        },
        {
            originalName: 'email_marketing_integration_docs.pdf',
            name: 'Email Marketing Integration Docs',
            type: 'document',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/email_marketing_integration_docs.pdf`,
            size: getRandomFileSize(150, 300),
            ...ids,
        },
        {
            originalName: 'urbanflow_font_package.zip',
            name: 'UrbanFlow Font Package',
            type: 'archive',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/urbanflow_font_package.zip`,
            size: getRandomFileSize(500, 1000),
            ...ids,
        },
        {
            originalName: 'past_campaign_performance_data.xlsx',
            name: 'Past Campaign Performance Data',
            type: 'spreadsheet',
            category: 'asset',
            link: 'https://docs.google.com/spreadsheets/d/urbanflow_past_campaigns',
            ...ids,
        },
        {
            originalName: 'client_meeting_notes_june_7.pdf',
            name: 'Client Meeting Notes (June 7)',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/client_meeting_notes_june_7.pdf`,
            size: getRandomFileSize(80, 150),
            ...ids,
        },
    ];
};

export const generateNewClassScheduleDesignPrintProductionFiles = (
    ids: Ids,
) => {
    const projectKebabCase = 'new-class-schedule-design-print-production';

    return [
        {
            originalName: 'class_schedule_design_brief.pdf',
            name: 'Class Schedule Design Brief',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/class_schedule_design_brief.pdf`,
            size: getRandomFileSize(200, 400),
            ...ids,
        },
        {
            originalName: 'final_schedule_design_print_ready.ai',
            name: 'Final Schedule Design (Print-Ready)',
            type: 'design',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/final_schedule_design_print_ready.ai`,
            size: getRandomFileSize(5000, 10000),
            ...ids,
        },
        {
            originalName: 'printer_quote_comparison_urbanflow.xlsx',
            name: 'Printer Quote Comparison',
            type: 'spreadsheet',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/printer_quote_comparison_urbanflow.xlsx`,
            size: getRandomFileSize(80, 150),
            ...ids,
        },
        {
            originalName: 'print_production_timeline.pdf',
            name: 'Print Production Timeline',
            type: 'document',
            category: 'work',
            link: 'https://example.com/urbanflow_print_timeline.pdf',
            ...ids,
        },
        {
            originalName: 'final_approval_form_schedule.pdf',
            name: 'Final Approval Form',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/final_approval_form_schedule.pdf`,
            size: getRandomFileSize(50, 100),
            ...ids,
        },
        {
            originalName: 'delivery_tracking_details.xlsx',
            name: 'Delivery Tracking Details',
            type: 'spreadsheet',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/delivery_tracking_details.xlsx`,
            size: getRandomFileSize(40, 80),
            ...ids,
        },
        {
            originalName: 'follow_up_email_template_client.docx',
            name: 'Client Follow-Up Email Template',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/follow_up_email_template_client.docx`,
            size: getRandomFileSize(20, 50),
            ...ids,
        },
        {
            originalName: 'old_class_schedule_references.pdf',
            name: 'Old Class Schedule References',
            type: 'document',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/old_class_schedule_references.pdf`,
            size: getRandomFileSize(150, 300),
            ...ids,
        },
        {
            originalName: 'urbanflow_class_offerings_list.xlsx',
            name: 'UrbanFlow Class Offerings List',
            type: 'spreadsheet',
            category: 'asset',
            link: 'https://docs.google.com/spreadsheets/d/urbanflow_class_list',
            ...ids,
        },
        {
            originalName: 'urbanflow_logo_and_brand_elements.zip',
            name: 'UrbanFlow Logo & Brand Elements',
            type: 'archive',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/urbanflow_logo_and_brand_elements.zip`,
            size: getRandomFileSize(2000, 5000),
            ...ids,
        },
        {
            originalName: 'printing_partner_contact_info.vcf',
            name: 'Printer Contact: Mr. Somchai',
            type: 'other',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/printing_partner_contact_info.vcf`,
            size: getRandomFileSize(5, 15),
            ...ids,
        },
        {
            originalName: 'paper_stock_samples_photos.zip',
            name: 'Paper Stock Samples',
            type: 'image',
            category: 'asset',
            link: 'https://photos.google.com/urbanflow_paper_samples',
            ...ids,
        },
        {
            originalName: 'urbanflow_studio_photos_high_res.zip',
            name: 'UrbanFlow Studio Photos (High-Res)',
            type: 'archive',
            category: 'asset',
            link: 'https://drive.google.com/drive/folders/urbanflow_studio_photos',
            ...ids,
        },
        {
            originalName: 'font_licensing_details.pdf',
            name: 'Font Licensing Details',
            type: 'document',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/font_licensing_details.pdf`,
            size: getRandomFileSize(70, 140),
            ...ids,
        },
    ];
};

export const generateMemberLoyaltyProgramBrandingFiles = (ids: Ids) => {
    const projectKebabCase = 'member-loyalty-program-branding';

    return [
        {
            originalName: 'loyalty_program_brief_urbanflow.pdf',
            name: 'Loyalty Program Project Brief',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/loyalty_program_brief_urbanflow.pdf`,
            size: getRandomFileSize(300, 600),
            ...ids,
        },
        {
            originalName: 'concept_designs_batch_1.zip',
            name: 'Initial Concept Designs (Batch 1)',
            type: 'design',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/concept_designs_batch_1.zip`,
            size: getRandomFileSize(10000, 20000),
            ...ids,
        },
        {
            originalName: 'client_feedback_summary_may20.xlsx',
            name: 'Client Feedback Summary (May 20)',
            type: 'spreadsheet',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/client_feedback_summary_may20.xlsx`,
            size: getRandomFileSize(80, 150),
            ...ids,
        },
        {
            originalName: 'follow_up_email_ms_ploy_template.docx',
            name: 'Follow-Up Email Template (Ms. Ploy)',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/follow_up_email_ms_ploy_template.docx`,
            size: getRandomFileSize(20, 50),
            ...ids,
        },
        {
            originalName: 'loyalty_program_tiers_benefits_draft.pdf',
            name: 'Loyalty Program Tiers & Benefits Draft',
            type: 'document',
            category: 'work',
            link: 'https://example.com/urbanflow_loyalty_tiers_draft.pdf',
            ...ids,
        },
        {
            originalName: 'branding_presentation_on_hold.pptx',
            name: 'Branding Presentation (On-Hold)',
            type: 'presentation',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/branding_presentation_on_hold.pptx`,
            size: getRandomFileSize(700, 1500),
            ...ids,
        },
        {
            originalName: 'restart_discussion_notes_june.docx',
            name: 'Restart Discussion Notes (June)',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/restart_discussion_notes_june.docx`,
            size: getRandomFileSize(50, 100),
            ...ids,
        },
        {
            originalName: 'competitor_loyalty_programs_research.pdf',
            name: 'Competitor Loyalty Programs Research',
            type: 'document',
            category: 'asset',
            link: 'https://example.com/urbanflow_competitor_loyalty_research.pdf',
            ...ids,
        },
        {
            originalName: 'urbanflow_member_demographics.xlsx',
            name: 'UrbanFlow Member Demographics',
            type: 'spreadsheet',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/urbanflow_member_demographics.xlsx`,
            size: getRandomFileSize(100, 200),
            ...ids,
        },
        {
            originalName: 'urbanflow_brand_elements_loyalty.zip',
            name: 'UrbanFlow Brand Elements (Loyalty)',
            type: 'archive',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/urbanflow_brand_elements_loyalty.zip`,
            size: getRandomFileSize(3000, 7000),
            ...ids,
        },
        {
            originalName: 'customer_retention_strategies.pdf',
            name: 'Customer Retention Strategies Guide',
            type: 'document',
            category: 'asset',
            link: 'https://example.com/customer_retention_guide.pdf',
            ...ids,
        },
        {
            originalName: 'ms_ploy_contact_details.vcf',
            name: 'Ms. Ploy Contact Details',
            type: 'other',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/ms_ploy_contact_details.vcf`,
            size: getRandomFileSize(5, 15),
            ...ids,
        },
        {
            originalName: 'crm_system_loyalty_module_docs.pdf',
            name: 'CRM System Loyalty Module Documentation',
            type: 'document',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/crm_system_loyalty_module_docs.pdf`,
            size: getRandomFileSize(200, 400),
            ...ids,
        },
        {
            originalName: 'focus_group_feedback_notes.pdf',
            name: 'Focus Group Feedback Notes',
            type: 'document',
            category: 'asset',
            link: 'https://docs.google.com/document/d/urbanflow_focus_group_feedback',
            ...ids,
        },
        {
            originalName: 'loyalty_program_incentive_ideas.xlsx',
            name: 'Loyalty Program Incentive Ideas',
            type: 'spreadsheet',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/loyalty_program_incentive_ideas.xlsx`,
            size: getRandomFileSize(100, 200),
            ...ids,
        },
        {
            originalName: 'strategic_planning_session_minutes.pdf',
            name: 'Strategic Planning Session Minutes',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/strategic_planning_session_minutes.pdf`,
            size: getRandomFileSize(150, 300),
            ...ids,
        },
    ];
};

export const generateIntroductoryYogaVideoSeriesFiles = (ids: Ids) => {
    const projectKebabCase = 'introductory-yoga-video-series-3-videos';

    return [
        {
            originalName: 'yoga_video_series_brief.pdf',
            name: 'Yoga Video Series Brief',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/yoga_video_series_brief.pdf`,
            size: getRandomFileSize(300, 600),
            ...ids,
        },
        {
            originalName: 'script_video_1_beginners_flow_v2.docx',
            name: 'Script: Beginners Flow Video (Final)',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/script_video_1_beginners_flow_v2.docx`,
            size: getRandomFileSize(100, 200),
            ...ids,
        },
        {
            originalName: 'script_video_2_morning_stretch_v1.docx',
            name: 'Script: Morning Stretch Video',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/script_video_2_morning_stretch_v1.docx`,
            size: getRandomFileSize(90, 180),
            ...ids,
        },
        {
            originalName: 'script_video_3_evening_relax_v1.docx',
            name: 'Script: Evening Relax Video',
            type: 'document',
            category: 'work',
            link: 'https://docs.google.com/document/d/urbanflow_evening_relax_script',
            ...ids,
        },
        {
            originalName: 'filming_schedule_july_10_12.pdf',
            name: 'Filming Schedule (July 10-12)',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/filming_schedule_july_10_12.pdf`,
            size: getRandomFileSize(150, 300),
            ...ids,
        },
        {
            originalName: 'studio_booking_confirmation.pdf',
            name: 'Studio Booking Confirmation',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/studio_booking_confirmation.pdf`,
            size: getRandomFileSize(50, 100),
            ...ids,
        },
        {
            originalName: 'voice_over_artist_selection_criteria.docx',
            name: 'Voice-Over Artist Selection Criteria',
            type: 'document',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/voice_over_artist_selection_criteria.docx`,
            size: getRandomFileSize(30, 60),
            ...ids,
        },
        {
            originalName: 'urbanflow_instructor_bios.pdf',
            name: 'UrbanFlow Instructor Bios',
            type: 'document',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/urbanflow_instructor_bios.pdf`,
            size: getRandomFileSize(100, 200),
            ...ids,
        },
        {
            originalName: 'background_music_options_yoga.zip',
            name: 'Background Music Options (Yoga)',
            type: 'audio',
            category: 'asset',
            link: 'https://soundcloud.com/urbanflow_yoga_music',
            ...ids,
        },
        {
            originalName: 'yoga_pose_reference_images.zip',
            name: 'Yoga Pose Reference Images',
            type: 'archive',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/yoga_pose_reference_images.zip`,
            size: getRandomFileSize(8000, 15000),
            ...ids,
        },
        {
            originalName: 'filming_equipment_list.pdf',
            name: 'Filming Equipment List',
            type: 'document',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/filming_equipment_list.pdf`,
            size: getRandomFileSize(150, 300),
            ...ids,
        },
        {
            originalName: 'target_audience_demographics_yoga.pdf',
            name: 'Target Audience Demographics',
            type: 'document',
            category: 'asset',
            link: 'https://example.com/urbanflow_yoga_audience.pdf',
            ...ids,
        },
        {
            originalName: 'urbanflow_brand_video_guidelines.pdf',
            name: 'UrbanFlow Brand Video Guidelines',
            type: 'document',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/urbanflow_brand_video_guidelines.pdf`,
            size: getRandomFileSize(200, 400),
            ...ids,
        },
        {
            originalName: 'video_editing_software_licenses.pdf',
            name: 'Video Editing Software Licenses',
            type: 'document',
            category: 'asset',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/video_editing_software_licenses.pdf`,
            size: getRandomFileSize(80, 150),
            ...ids,
        },
        {
            originalName: 'marketing_distribution_plan_draft.pptx',
            name: 'Marketing Distribution Plan Draft',
            type: 'presentation',
            category: 'work',
            link: 'https://docs.google.com/presentation/d/urbanflow_video_marketing_plan',
            ...ids,
        },
        {
            originalName: 'post_production_checklist.xlsx',
            name: 'Post-Production Checklist',
            type: 'spreadsheet',
            category: 'work',
            s3Key: `${ids.userId}/projects/${projectKebabCase}/post_production_checklist.xlsx`,
            size: getRandomFileSize(60, 120),
            ...ids,
        },
    ];
};

export const getUrbanFlowFitnessFiles = (ids: Ids) => {
    const urbanFlowFitnessFileGenerators: [string, any][] = [
        [
            'Summer Challenge Landing Page & Ad Creatives',
            generateSummerChallengeLandingPageAdCreativesFiles,
        ],
        [
            'New Class Schedule Design & Print Production',
            generateNewClassScheduleDesignPrintProductionFiles,
        ],
        [
            'Member Loyalty Program Branding',
            generateMemberLoyaltyProgramBrandingFiles,
        ],
        [
            'Introductory Yoga Video Series (3 videos)',
            generateIntroductoryYogaVideoSeriesFiles,
        ],
    ];

    return urbanFlowFitnessFileGenerators.flatMap(
        ([projectTitle, generateFn]) => {
            const projectIds = ids[projectTitle];

            if (!projectIds) {
                console.warn(
                    `Warning: IDs not found for project: "${projectTitle}" for Urban Flow Fitness. No files generated.`,
                );
                return [];
            }

            return generateFn(projectIds);
        },
    );
};
