export const mockUser = {
   id: '1a2b3c4d-1234-5678-9101-abcdefabcdef',
   email: 'johndoe@example.com',
   displayName: 'John Doe',
   password: '$2b$12$2bhJSAf6Qg68Y/sVrd9sNOzkYCo4k/vXuLTkrxCO/VrtU/AttQvw6',
   specialization: ['Graphic Design', 'Illustration'],
   bio: 'Freelance graphic designer specializing in branding and illustrations.',
   phoneNumber: '+1234567890',
   address: '123 Main St, New York, NY',
   avatar: 'https://example.com/avatar1.jpg',
   pinnedProjects: ['p1', 'p2'],
   currency: 'USD',
   quitting: false,
   createdAt: new Date('2025-03-12T10:00:00.000Z'), // ✅ Convert to Date
   updatedAt: new Date('2025-03-12T10:00:00.000Z'), // ✅ Convert to Date
   refreshTokens: [],
   projects: [],
   clients: [],
   partnerCompanies: [],
   clientContacts: [],
   partnerContacts: [],
   salesDocuments: [],
   files: [],
   tasks: [],
   events: [],
   authProvider: ['email'],
};
