export const getSeedSalesDocumentFileData = (
    userId: string,
    projectId: string,
    clientId: string,
) => {
    return {
        originalName: 'invoice_april.pdf',
        displayName: 'Invoice April',
        type: 'pdf',
        category: 'Invoice',
        link: 'https://s3.amazonaws.com/bucket/invoice_april.pdf',
        s3Key: 'files/invoice_april.pdf',
        size: 1048576,
    };
};

export const getSeedSalesDocumentData = (
    userId: string,
    projectId: string,
    clientId: string,
) => [
    {
        title: 'Website Redesign Quotation',
        category: 'quotation',
        number: 'Q-2025-001',
        issuedAt: new Date('2025-04-10').toISOString(),
        currency: 'THB',
        referenceNumber: 'REF-Q001',
        projectDescription: 'Redesign of e-commerce website UI/UX',
        selectedProjectClientId: 'client_proj_123',
        freelancerName: 'Niran S.',
        freelancerEmail: 'niran@example.com',
        freelancerPhone: '0812345678',
        freelancerTaxId: '1234567890123',
        freelancerDetail: 'Bangkok-based freelance web designer',
        clientName: 'Acme Corp.',
        clientTaxId: '9876543210987',
        clientAddress: '123 Sukhumvit Rd, Bangkok',
        clientPhone: '022345678',
        clientOffice: 'Acme HQ',
        clientDetail: 'Contact: Jane Doe (Marketing)',
        subtotal: 50000,
        discount: 5000,
        tax: 3325,
        total: 48325,
        customAdjustment: 0,
        note: 'Quotation valid for 30 days',
    },
    {
        title: 'Website Redesign Quotation',
        category: 'invoice',
        number: 'INV-2025-001',
        issuedAt: new Date('2025-04-11').toISOString(),
        currency: 'THB',
        referenceNumber: 'REF-I001',
        projectDescription: 'Redesign of e-commerce website UI/UX',
        selectedProjectClientId: 'client_proj_123',
        freelancerName: 'Niran S.',
        freelancerEmail: 'niran@example.com',
        freelancerPhone: '0812345678',
        freelancerTaxId: '1234567890123',
        freelancerDetail: 'Bangkok-based freelance web designer',
        clientName: 'Acme Corp.',
        clientTaxId: '9876543210987',
        clientAddress: '123 Sukhumvit Rd, Bangkok',
        clientPhone: '022345678',
        clientOffice: 'Acme HQ',
        clientDetail: 'Contact: Jane Doe (Marketing)',
        subtotal: 50000,
        discount: 5000,
        tax: 3325,
        total: 48325,
        customAdjustment: 0,
        note: 'Due in 15 days',
    },
    {
        title: 'Website Redesign Quotation',
        category: 'receipt',
        number: 'RCPT-2025-001',
        issuedAt: new Date('2025-04-12').toISOString(),
        currency: 'THB',
        referenceNumber: 'REF-R001',
        projectDescription: 'Redesign of e-commerce website UI/UX',
        selectedProjectClientId: 'client_proj_123',
        freelancerName: 'Niran S.',
        freelancerEmail: 'niran@example.com',
        freelancerPhone: '0812345678',
        freelancerTaxId: '1234567890123',
        freelancerDetail: 'Bangkok-based freelance web designer',
        clientName: 'Acme Corp.',
        clientTaxId: '9876543210987',
        clientAddress: '123 Sukhumvit Rd, Bangkok',
        clientPhone: '022345678',
        clientOffice: 'Acme HQ',
        clientDetail: 'Contact: Jane Doe (Marketing)',
        subtotal: 50000,
        discount: 5000,
        tax: 3325,
        total: 48325,
        customAdjustment: 0,
        note: 'Full payment received via bank transfer',
    },
];
