export const getSalesDocumentItemsData = (
    userId: string,
    parentDocumentId: string,
) => [
    {
        userId,
        parentDocumentId,
        title: 'Homepage Redesign',
        description: 'Modern UI for homepage with improved UX flow',
        rate: 15000,
        quantity: 1,
    },
    {
        userId,
        parentDocumentId,
        title: 'Product Page Layout',
        description: 'Revamp product detail and listing pages',
        rate: 10000,
        quantity: 1,
    },
    {
        userId,
        parentDocumentId,
        title: 'Mobile Responsiveness',
        description: 'Ensure fully responsive design across devices',
        rate: 8000,
        quantity: 1,
    },
    {
        userId,
        parentDocumentId,
        title: 'Design System Setup',
        description: 'Create reusable components and design tokens',
        rate: 12000,
        quantity: 1,
    },
    {
        userId,
        parentDocumentId,
        title: 'Client Revisions',
        description: 'Up to 3 rounds of revisions included',
        rate: 5000,
        quantity: 1,
    },
];
