interface companyIdObject {
    [key: string]: string;
}

export function getPartnerContacts(userId: string, companyId: companyIdObject) {
    return [
        ...seedMomentumStudioContacts(userId, companyId),
        ...seedVisionaryTalentAgencyContacts(userId, companyId),
        ...seedEchoMediaGroupContacts(userId, companyId),
        ...seedFlickerFilmsContacts(userId, companyId),
        ...seedPulseCreativeContacts(userId, companyId),
        ...seedZenithTalentContacts(userId, companyId),
        ...seedFreelancersContactsData(userId, companyId),
    ];
}

const seedMomentumStudioContacts = (
    userId: string,
    companyId: companyIdObject,
) => [
    {
        userId: userId,
        name: 'Aiden Somprasert',
        company: 'Momentum Studios',
        role: 'Project Manager',
        phoneNumber: '0812345678',
        email: 'aiden.s@momentum.com',
        details: 'Main contact for ongoing projects.',
        avatar: '/avatars/aiden.png',
    },
    {
        userId: userId,
        name: 'Lena Tan',
        company: 'Momentum Studios',
        role: 'Graphic Designer',
        phoneNumber: '0898765432',
        email: 'lena.t@momentum.com',
        details: 'Specializes in motion graphics.',
        avatar: '/avatars/lena.png',
    },
    {
        userId: userId,
        name: 'Thanakorn Wells',
        company: 'Momentum Studios',
        role: 'UX Consultant',
        phoneNumber: '0861112233',
        email: 'thanakorn.w@momentum.com',
        details: 'Focuses on cross-platform UX.',
        avatar: '/avatars/thanakorn.png',
    },
    {
        userId: userId,
        name: 'Emily Kanchana',
        company: 'Momentum Studios',
        role: 'Producer',
        phoneNumber: '0823456789',
        email: 'emily.k@momentum.com',
        details: 'Coordinates production timelines.',
        avatar: '/avatars/emily.png',
    },
    {
        userId: userId,
        name: 'Krit Riley',
        company: 'Momentum Studios',
        role: 'Copywriter',
        phoneNumber: '0876543210',
        email: 'krit.r@momentum.com',
        details: 'Handles all English campaign copy.',
        avatar: '/avatars/krit.png',
    },
    {
        userId: userId,
        name: 'Jasmine Panus',
        company: 'Momentum Studios',
        role: 'Retoucher',
        phoneNumber: '0854321987',
        email: 'jasmine.p@momentum.com',
        details: 'Handles post-production for fashion shoots.',
        avatar: '/avatars/jasmine.png',
    },
    {
        userId: userId,
        name: 'Nico Chatchai',
        company: 'Momentum Studios',
        role: 'Animator',
        phoneNumber: '0832145698',
        email: 'nico.c@momentum.com',
        details: '2D/3D animation specialist.',
        avatar: '/avatars/nico.png',
    },
    {
        userId: userId,
        name: 'May Lin',
        company: 'Momentum Studios',
        role: 'Visual Strategist',
        phoneNumber: '0803214569',
        email: 'may.l@momentum.com',
        details: 'Creates visual direction decks.',
        avatar: '/avatars/may.png',
    },
    {
        userId: userId,
        name: 'Tawan Hughes',
        company: 'Momentum Studios',
        role: 'Art Director',
        phoneNumber: '0893219876',
        email: 'tawan.h@momentum.com',
        details: 'Leads creative concepting.',
        avatar: '/avatars/tawan.png',
    },
    {
        userId: userId,
        name: 'Isla Rattanakorn',
        company: 'Momentum Studios',
        role: 'Client Liaison',
        phoneNumber: '0841239876',
        email: 'isla.r@momentum.com',
        details: 'Handles client communication.',
        avatar: '/avatars/isla.png',
    },
];

const seedVisionaryTalentAgencyContacts = (
    userId: string,
    company 
) => [
    {
        userId: userId,
        name: 'Maya Vorakorn',
        company: 'Visionary Talent Agency',
        role: 'Talent Manager',
        phoneNumber: '0812345678',
        email: 'maya.v@visionarytalent.com',
        details: 'Oversees talent recruitment and management.',
        avatar: '/avatars/maya.png',
    },
    {
        userId: userId,
        name: 'Jonas Reid',
        company: 'Visionary Talent Agency',
        role: 'Casting Director',
        phoneNumber: '0898765432',
        email: 'jonas.r@visionarytalent.com',
        details: 'In charge of casting for projects.',
        avatar: '/avatars/jonas.png',
    },
    {
        userId: userId,
        name: 'Suriya Marlowe',
        company: 'Visionary Talent Agency',
        role: 'PR Specialist',
        phoneNumber: '0861112233',
        email: 'suriya.m@visionarytalent.com',
        details: 'Manages public relations and media.',
        avatar: '/avatars/suriya.png',
    },
    {
        userId: userId,
        name: 'Ella Tanaka',
        company: 'Visionary Talent Agency',
        role: 'Creative Director',
        phoneNumber: '0823456789',
        email: 'ella.t@visionarytalent.com',
        details: 'Leads creative direction for talent branding.',
        avatar: '/avatars/ella.png',
    },
    {
        userId: userId,
        name: 'Kai Rivera',
        company: 'Visionary Talent Agency',
        role: 'Marketing Lead',
        phoneNumber: '0876543210',
        email: 'kai.r@visionarytalent.com',
        details: 'Responsible for marketing campaigns.',
        avatar: '/avatars/kai.png',
    },
    {
        userId: userId,
        name: 'Liam Chantachai',
        company: 'Visionary Talent Agency',
        role: 'Talent Scout',
        phoneNumber: '0854321987',
        email: 'liam.c@visionarytalent.com',
        details: 'Scouts for new talent in the industry.',
        avatar: '/avatars/liam.png',
    },
    {
        userId: userId,
        name: 'Ava Leung',
        company: 'Visionary Talent Agency',
        role: 'Event Coordinator',
        phoneNumber: '0832145698',
        email: 'ava.l@visionarytalent.com',
        details: 'Coordinates events and client meetings.',
        avatar: '/avatars/ava.png',
    },
    {
        userId: userId,
        name: 'Mick Sycamore',
        company: 'Visionary Talent Agency',
        role: 'Head of Operations',
        phoneNumber: '0803214569',
        email: 'mick.s@visionarytalent.com',
        details: 'Oversees operations and project execution.',
        avatar: '/avatars/mick.png',
    },
    {
        userId: userId,
        name: 'Noah Phan',
        company: 'Visionary Talent Agency',
        role: 'Business Development',
        phoneNumber: '0893219876',
        email: 'noah.p@visionarytalent.com',
        details: 'Expands business opportunities and partnerships.',
        avatar: '/avatars/noah.png',
    },
    {
        userId: userId,
        name: 'Hana Rattanakul',
        company: 'Visionary Talent Agency',
        role: 'Digital Strategist',
        phoneNumber: '0841239876',
        email: 'hana.r@visionarytalent.com',
        details: 'Leads digital marketing strategies.',
        avatar: '/avatars/hana.png',
    },
];

const seedEchoMediaGroupContacts = (
    userId: string,
    company 
) => [
    {
        userId: userId,
        name: 'Ryuji Kato',
        company: 'Echo Media Group',
        role: 'Media Strategist',
        phoneNumber: '0812345678',
        email: 'ryuji.k@echomedia.com',
        details: 'Develops and implements media strategies.',
        avatar: '/avatars/ryuji.png',
    },
    {
        userId: userId,
        name: 'Siti Amira',
        company: 'Echo Media Group',
        role: 'Content Creator',
        phoneNumber: '0898765432',
        email: 'siti.a@echomedia.com',
        details: 'Produces engaging content for social media.',
        avatar: '/avatars/siti.png',
    },
    {
        userId: userId,
        name: 'Takumi Hirata',
        company: 'Echo Media Group',
        role: 'Creative Director',
        phoneNumber: '0861112233',
        email: 'takumi.h@echomedia.com',
        details: 'Leads the creative direction for campaigns.',
        avatar: '/avatars/takumi.png',
    },
    {
        userId: userId,
        name: 'Indra Puspita',
        company: 'Echo Media Group',
        role: 'Marketing Specialist',
        phoneNumber: '0823456789',
        email: 'indra.p@echomedia.com',
        details: 'Focuses on digital marketing strategies.',
        avatar: '/avatars/indra.png',
    },
    {
        userId: userId,
        name: 'Aya Fujimoto',
        company: 'Echo Media Group',
        role: 'PR Manager',
        phoneNumber: '0876543210',
        email: 'aya.f@echomedia.com',
        details: 'Manages public relations and client outreach.',
        avatar: '/avatars/aya.png',
    },
    {
        userId: userId,
        name: 'Rafiq Syahran',
        company: 'Echo Media Group',
        role: 'SEO Expert',
        phoneNumber: '0854321987',
        email: 'rafiq.s@echomedia.com',
        details: 'Improves search engine rankings for campaigns.',
        avatar: '/avatars/rafiq.png',
    },
    {
        userId: userId,
        name: 'Haruka Nishida',
        company: 'Echo Media Group',
        role: 'Graphic Designer',
        phoneNumber: '0832145698',
        email: 'haruka.n@echomedia.com',
        details: 'Designs visual content for media projects.',
        avatar: '/avatars/haruka.png',
    },
    {
        userId: userId,
        name: 'Putri Ayu',
        company: 'Echo Media Group',
        role: 'Event Coordinator',
        phoneNumber: '0803214569',
        email: 'putri.a@echomedia.com',
        details: 'Coordinates events and promotional activities.',
        avatar: '/avatars/putri.png',
    },
    {
        userId: userId,
        name: 'Yuto Takahashi',
        company: 'Echo Media Group',
        role: 'Business Development Manager',
        phoneNumber: '0893219876',
        email: 'yuto.t@echomedia.com',
        details: 'Leads business development and partnerships.',
        avatar: '/avatars/yuto.png',
    },
    {
        userId: userId,
        name: 'Lina Sari',
        company: 'Echo Media Group',
        role: 'Social Media Manager',
        phoneNumber: '0841239876',
        email: 'lina.s@echomedia.com',
        details: 'Manages and grows social media channels.',
        avatar: '/avatars/lina.png',
    },
];

const seedFlickerFilmsContacts = (
    userId: string,
    company 
) => [
    {
        userId: userId,
        name: 'Ethan Panya',
        company: 'Flicker Films',
        role: 'Director of Photography',
        phoneNumber: '0812345678',
        email: 'ethan.p@flickerfilms.com',
        details: 'Responsible for the visual look of all productions.',
        avatar: '/avatars/ethan.png',
    },
    {
        userId: userId,
        name: 'Lily Nguyen',
        company: 'Flicker Films',
        role: 'Production Designer',
        phoneNumber: '0898765432',
        email: 'lily.n@flickerfilms.com',
        details: 'Designs sets and props for films.',
        avatar: '/avatars/lily.png',
    },
    {
        userId: userId,
        name: 'Victor Liu',
        company: 'Flicker Films',
        role: 'Sound Engineer',
        phoneNumber: '0861112233',
        email: 'victor.l@flickerfilms.com',
        details: 'Handles all aspects of sound during production.',
        avatar: '/avatars/victor.png',
    },
    {
        userId: userId,
        name: 'Chloe Jensen',
        company: 'Flicker Films',
        role: 'Editor',
        phoneNumber: '0823456789',
        email: 'chloe.j@flickerfilms.com',
        details: 'Manages post-production editing and finishing.',
        avatar: '/avatars/chloe.png',
    },
    {
        userId: userId,
        name: 'Maxim Santi',
        company: 'Flicker Films',
        role: 'Producer',
        phoneNumber: '0876543210',
        email: 'maxim.s@flickerfilms.com',
        details: 'Oversees film production from start to finish.',
        avatar: '/avatars/maxim.png',
    },
    {
        userId: userId,
        name: 'Tara Wissakorn',
        company: 'Flicker Films',
        role: 'Casting Agent',
        phoneNumber: '0854321987',
        email: 'tara.w@flickerfilms.com',
        details: 'Manages talent recruitment and casting calls.',
        avatar: '/avatars/tara.png',
    },
    {
        userId: userId,
        name: 'Sophie Dhanakorn',
        company: 'Flicker Films',
        role: 'Art Director',
        phoneNumber: '0832145698',
        email: 'sophie.d@flickerfilms.com',
        details: 'Leads the design and aesthetic vision of the film.',
        avatar: '/avatars/sophie.png',
    },
    {
        userId: userId,
        name: 'Jackie Thanh',
        company: 'Flicker Films',
        role: 'Script Supervisor',
        phoneNumber: '0803214569',
        email: 'jackie.t@flickerfilms.com',
        details: 'Ensures continuity and quality of scripts during filming.',
        avatar: '/avatars/jackie.png',
    },
    {
        userId: userId,
        name: 'Ravi Arun',
        company: 'Flicker Films',
        role: 'Camera Operator',
        phoneNumber: '0893219876',
        email: 'ravi.a@flickerfilms.com',
        details: 'Operates cameras for film shoots.',
        avatar: '/avatars/ravi.png',
    },
    {
        userId: userId,
        name: 'Ivy Rattanai',
        company: 'Flicker Films',
        role: 'Visual Effects Artist',
        phoneNumber: '0841239876',
        email: 'ivy.r@flickerfilms.com',
        details: 'Creates and integrates visual effects into films.',
        avatar: '/avatars/ivy.png',
    },
];

const seedPulseCreativeContacts = (
    userId: string,
    company 
) => [
    {
        userId: userId,
        name: 'Noah Chai',
        company: 'Pulse Creative',
        role: 'Creative Director',
        phoneNumber: '0812345678',
        email: 'noah.c@pulsecreative.com',
        details: 'Leads the creative vision and concept development.',
        avatar: '/avatars/noah.png',
    },
    {
        userId: userId,
        name: 'Amara Srisuk',
        company: 'Pulse Creative',
        role: 'Graphic Designer',
        phoneNumber: '0898765432',
        email: 'amara.s@pulsecreative.com',
        details: 'Designs branding and visual identities.',
        avatar: '/avatars/amara.png',
    },
    {
        userId: userId,
        name: 'Ethan Wongsak',
        company: 'Pulse Creative',
        role: 'Photographer',
        phoneNumber: '0861112233',
        email: 'ethan.w@pulsecreative.com',
        details: 'Specializes in lifestyle and fashion photography.',
        avatar: '/avatars/ethan.png',
    },
    {
        userId: userId,
        name: 'Lara Viroj',
        company: 'Pulse Creative',
        role: 'Web Developer',
        phoneNumber: '0823456789',
        email: 'lara.v@pulsecreative.com',
        details: 'Develops websites and user interfaces.',
        avatar: '/avatars/lara.png',
    },
    {
        userId: userId,
        name: 'Dylan Raj',
        company: 'Pulse Creative',
        role: 'Motion Graphics Artist',
        phoneNumber: '0876543210',
        email: 'dylan.r@pulsecreative.com',
        details: 'Creates dynamic visual content and animations.',
        avatar: '/avatars/dylan.png',
    },
    {
        userId: userId,
        name: 'Mei Jing',
        company: 'Pulse Creative',
        role: 'Copywriter',
        phoneNumber: '0854321987',
        email: 'mei.j@pulsecreative.com',
        details: 'Crafts compelling marketing and advertising copy.',
        avatar: '/avatars/mei.png',
    },
    {
        userId: userId,
        name: 'Liam Song',
        company: 'Pulse Creative',
        role: 'Account Manager',
        phoneNumber: '0832145698',
        email: 'liam.s@pulsecreative.com',
        details: 'Manages client relationships and project coordination.',
        avatar: '/avatars/liam.png',
    },
    {
        userId: userId,
        name: 'Sophia Phan',
        company: 'Pulse Creative',
        role: 'Social Media Manager',
        phoneNumber: '0803214569',
        email: 'sophia.p@pulsecreative.com',
        details: 'Handles social media marketing and content strategy.',
        avatar: '/avatars/sophia.png',
    },
    {
        userId: userId,
        name: 'Alex Tan',
        company: 'Pulse Creative',
        role: 'UI/UX Designer',
        phoneNumber: '0893219876',
        email: 'alex.t@pulsecreative.com',
        details: 'Designs user interfaces with a focus on user experience.',
        avatar: '/avatars/alex.png',
    },
    {
        userId: userId,
        name: 'Grace Suthida',
        company: 'Pulse Creative',
        role: 'Event Coordinator',
        phoneNumber: '0841239876',
        email: 'grace.s@pulsecreative.com',
        details: 'Plans and coordinates events for client campaigns.',
        avatar: '/avatars/grace.png',
    },
];

const seedZenithTalentContacts = (
    userId: string,
    company 
) => [
    {
        userId: userId,
        name: 'Maya Singh',
        company: 'Zenith Talent',
        role: 'Talent Manager',
        phoneNumber: '0812345678',
        email: 'maya.s@zenithtalent.com',
        details: 'Manages client talent acquisition and relations.',
        avatar: '/avatars/maya.png',
    },
    {
        userId: userId,
        name: 'Lucas Wong',
        company: 'Zenith Talent',
        role: 'Casting Director',
        phoneNumber: '0898765432',
        email: 'lucas.w@zenithtalent.com',
        details: 'Oversees the casting of talents for roles.',
        avatar: '/avatars/lucas.png',
    },
    {
        userId: userId,
        name: 'Nina Jirawat',
        company: 'Zenith Talent',
        role: 'PR Manager',
        phoneNumber: '0861112233',
        email: 'nina.j@zenithtalent.com',
        details: 'Handles public relations and media outreach.',
        avatar: '/avatars/nina.png',
    },
    {
        userId: userId,
        name: 'Jaxon Charoen',
        company: 'Zenith Talent',
        role: 'Creative Director',
        phoneNumber: '0823456789',
        email: 'jaxon.c@zenithtalent.com',
        details: 'Guides creative direction for all talent projects.',
        avatar: '/avatars/jaxon.png',
    },
    {
        userId: userId,
        name: 'Olivia Narin',
        company: 'Zenith Talent',
        role: 'Marketing Specialist',
        phoneNumber: '0876543210',
        email: 'olivia.n@zenithtalent.com',
        details: 'Manages marketing campaigns and promotions.',
        avatar: '/avatars/olivia.png',
    },
    {
        userId: userId,
        name: 'Ethan Pravit',
        company: 'Zenith Talent',
        role: 'Talent Scout',
        phoneNumber: '0854321987',
        email: 'ethan.p@zenithtalent.com',
        details: 'Scouts new and emerging talent for the agency.',
        avatar: '/avatars/ethan.png',
    },
    {
        userId: userId,
        name: 'Ava Han',
        company: 'Zenith Talent',
        role: 'Event Coordinator',
        phoneNumber: '0832145698',
        email: 'ava.h@zenithtalent.com',
        details: 'Organizes talent events, meetings, and engagements.',
        avatar: '/avatars/ava.png',
    },
    {
        userId: userId,
        name: 'Samuel Panya',
        company: 'Zenith Talent',
        role: 'Operations Manager',
        phoneNumber: '0803214569',
        email: 'samuel.p@zenithtalent.com',
        details: 'Ensures smooth operations within the agency.',
        avatar: '/avatars/samuel.png',
    },
    {
        userId: userId,
        name: 'Isabella Pramoj',
        company: 'Zenith Talent',
        role: 'Client Relations',
        phoneNumber: '0893219876',
        email: 'isabella.p@zenithtalent.com',
        details: 'Maintains strong relationships with clients and partners.',
        avatar: '/avatars/isabella.png',
    },
    {
        userId: userId,
        name: 'Liam Rattanapong',
        company: 'Zenith Talent',
        role: 'Talent Development',
        phoneNumber: '0841239876',
        email: 'liam.r@zenithtalent.com',
        details: 'Develops and mentors talent to maximize their potential.',
        avatar: '/avatars/liam.png',
    },
];

const seedFreelancersContactsData = (
    userId: string,
    company 
) => [
    {
        userId: userId,
        name: 'Somchai Jansen',
        company: 'Freelancers',
        role: 'Web Developer',
        phoneNumber: '0931234567',
        email: 'somchai.j@freelancers.com',
        details: 'Expert in full-stack JavaScript development.',
        avatar: 'https://randomuser.me/api/portraits/men/6.jpg',
    },
    {
        userId: userId,
        name: 'Anaïs Chaiyapat',
        company: 'Freelancers',
        role: 'SEO Specialist',
        phoneNumber: '0849876543',
        email: 'anais.c@freelancers.com',
        details: 'Focuses on website optimization and content strategy.',
        avatar: 'https://randomuser.me/api/portraits/women/6.jpg',
    },
    {
        userId: userId,
        name: 'Viktor Sittichai',
        company: 'Freelancers',
        role: 'Graphic Designer',
        phoneNumber: '0881237890',
        email: 'viktor.s@freelancers.com',
        details: 'Creates brand identities and digital artwork.',
        avatar: 'https://randomuser.me/api/portraits/men/7.jpg',
    },
    {
        userId: userId,
        name: 'Klara Thavisin',
        company: 'Freelancers',
        role: 'Content Writer',
        phoneNumber: '0865432109',
        email: 'klara.t@freelancers.com',
        details: 'Writes engaging and SEO-friendly content.',
        avatar: 'https://randomuser.me/api/portraits/women/7.jpg',
    },
    {
        userId: userId,
        name: 'Stefan Poom',
        company: 'Freelancers',
        role: 'App Developer',
        phoneNumber: '0857654321',
        email: 'stefan.p@freelancers.com',
        details: 'Creates mobile applications for iOS and Android.',
        avatar: 'https://randomuser.me/api/portraits/men/8.jpg',
    },
    {
        userId: userId,
        name: 'Chirawan Müller',
        company: 'Freelancers',
        role: 'Translator',
        phoneNumber: '0876543210',
        email: 'chirawan.m@freelancers.com',
        details: 'Specializes in Thai, English, and German translation.',
        avatar: 'https://randomuser.me/api/portraits/women/8.jpg',
    },
    {
        userId: userId,
        name: 'Franz Srisakda',
        company: 'Freelancers',
        role: 'Video Editor',
        phoneNumber: '0901234567',
        email: 'franz.s@freelancers.com',
        details: 'Expert in video post-production and animation.',
        avatar: 'https://randomuser.me/api/portraits/men/9.jpg',
    },
    {
        userId: userId,
        name: 'Charlotte Kittipong',
        company: 'Freelancers',
        role: 'Social Media Manager',
        phoneNumber: '0945678901',
        email: 'charlotte.k@freelancers.com',
        details: 'Manages social media accounts and campaigns.',
        avatar: 'https://randomuser.me/api/portraits/women/9.jpg',
    },
    {
        userId: userId,
        name: 'Nicolas Wichai',
        company: 'Freelancers',
        role: 'Photographer',
        phoneNumber: '0854321098',
        email: 'nicolas.w@freelancers.com',
        details: 'Specializes in event and portrait photography.',
        avatar: 'https://randomuser.me/api/portraits/men/10.jpg',
    },
    {
        userId: userId,
        name: 'Sasithorn Götz',
        company: 'Freelancers',
        role: 'UX/UI Designer',
        phoneNumber: '0898765432',
        email: 'sasithorn.g@freelancers.com',
        details: 'Designs intuitive user interfaces and experiences.',
        avatar: 'https://randomuser.me/api/portraits/women/10.jpg',
    },
    {
        userId: userId,
        name: 'Leo Suwan',
        company: 'Freelancers',
        role: 'Backend Developer',
        phoneNumber: '0912345678',
        email: 'leo.s@freelancers.com',
        details: 'Experienced in Node.js and database architecture.',
        avatar: 'https://randomuser.me/api/portraits/men/11.jpg',
    },
    {
        userId: userId,
        name: 'Mélanie Kittichai',
        company: 'Freelancers',
        role: 'Fashion Designer',
        phoneNumber: '0832123456',
        email: 'melanie.k@freelancers.com',
        details: 'Creates modern, sustainable fashion lines.',
        avatar: 'https://randomuser.me/api/portraits/women/11.jpg',
    },
    {
        userId: userId,
        name: 'Arvid Kunchai',
        company: 'Freelancers',
        role: 'Game Developer',
        phoneNumber: '0843126789',
        email: 'arvid.k@freelancers.com',
        details: 'Specializes in Unity and game mechanics.',
        avatar: 'https://randomuser.me/api/portraits/men/12.jpg',
    },
    {
        userId: userId,
        name: 'Sophie Pichai',
        company: 'Freelancers',
        role: 'Digital Marketer',
        phoneNumber: '0897654321',
        email: 'sophie.p@freelancers.com',
        details: 'Focuses on PPC and digital ad campaigns.',
        avatar: 'https://randomuser.me/api/portraits/women/12.jpg',
    },
    {
        userId: userId,
        name: 'Florian Supachai',
        company: 'Freelancers',
        role: 'AI Specialist',
        phoneNumber: '0865432178',
        email: 'florian.s@freelancers.com',
        details: 'Builds machine learning models for businesses.',
        avatar: 'https://randomuser.me/api/portraits/men/13.jpg',
    },
    {
        userId: userId,
        name: 'Julia Apichat',
        company: 'Freelancers',
        role: 'Illustrator',
        phoneNumber: '0876543210',
        email: 'julia.a@freelancers.com',
        details: 'Creates custom illustrations for branding.',
        avatar: 'https://randomuser.me/api/portraits/women/13.jpg',
    },
    {
        userId: userId,
        name: 'Jürgen Lertchai',
        company: 'Freelancers',
        role: 'Video Production',
        phoneNumber: '0857654321',
        email: 'jurgen.l@freelancers.com',
        details: 'Handles video production from start to finish.',
        avatar: 'https://randomuser.me/api/portraits/men/14.jpg',
    },
    {
        userId: userId,
        name: 'Kittisak Müller',
        company: 'Freelancers',
        role: 'Web Designer',
        phoneNumber: '0801234567',
        email: 'kittisak.m@freelancers.com',
        details: 'Designs clean, user-friendly websites.',
        avatar: 'https://randomuser.me/api/portraits/men/15.jpg',
    },
    {
        userId: userId,
        name: 'Ingrid Pairoj',
        company: 'Freelancers',
        role: 'Marketing Strategist',
        phoneNumber: '0936547890',
        email: 'ingrid.p@freelancers.com',
        details: 'Develops marketing strategies for global brands.',
        avatar: 'https://randomuser.me/api/portraits/women/14.jpg',
    },
    {
        userId: userId,
        name: 'Ethan Phanupong',
        company: 'Freelancers',
        role: 'Data Analyst',
        phoneNumber: '0896543210',
        email: 'ethan.p@freelancers.com',
        details: 'Analyzes large datasets to generate insights.',
        avatar: 'https://randomuser.me/api/portraits/men/16.jpg',
    },
];
