export const getSeedFilesDta = (
    userId: string,
    projectId: string,
    clientId: string,
) => [
    {
        originalName: 'LogoConcepts_v1.ai',
        displayName: 'Initial Logo Concepts',
        type: 'design',
        category: 'work',
        link: 'https://s3.aws.com/bilf/logo_v1',
        s3Key: 'logo_v1',
        projectId: projectId,
        clientId: clientId,
        userId: userId,
        size: 102400,
    },
    {
        originalName: 'BrandGuidelines.pdf',
        displayName: 'Brand Guidelines',
        type: 'document',
        category: 'work',
        link: 'https://s3.aws.com/bilf/brand_guide',
        s3Key: 'brand_guide',
        projectId: projectId,
        clientId: clientId,
        userId: userId,
        size: 512000,
    },
    {
        originalName: 'BusinessCard_Mockup.jpg',
        displayName: 'Business Card Mockup',
        type: 'image',
        category: 'asset',
        link: 'https://s3.aws.com/bilf/bcard_mockup',
        s3Key: 'bcard_mockup',
        projectId: projectId,
        clientId: clientId,
        userId: userId,
        size: 204800,
    },
    {
        originalName: 'ColorPalette.sketch',
        displayName: 'Color Palette Sketch',
        type: 'design',
        category: 'work',
        link: 'https://s3.aws.com/bilf/palette_sketch',
        s3Key: 'palette_sketch',
        projectId: projectId,
        clientId: clientId,
        userId: userId,
        size: 305000,
    },
    {
        originalName: 'TypographyOptions.pdf',
        displayName: 'Typography Options',
        type: 'document',
        category: 'work',
        link: 'https://s3.aws.com/bilf/typography',
        s3Key: 'typography',
        projectId: projectId,
        clientId: clientId,
        userId: userId,
        size: 123000,
    },
    {
        originalName: 'FinalLogo.ai',
        displayName: 'Final Logo',
        type: 'design',
        category: 'work',
        link: 'https://s3.aws.com/bilf/logo_final',
        s3Key: 'logo_final',
        projectId: projectId,
        clientId: clientId,
        userId: userId,
        size: 110000,
    },
    {
        originalName: 'Mockups.zip',
        displayName: 'All Mockups',
        type: 'archive',
        category: 'asset',
        link: 'https://s3.aws.com/bilf/mockups_zip',
        s3Key: 'mockups_zip',
        projectId: projectId,
        clientId: clientId,
        userId: userId,
        size: 1048576,
    },
    {
        originalName: 'PresentationDeck.pptx',
        displayName: 'Client Presentation',
        type: 'presentation',
        category: 'work',
        link: 'https://s3.aws.com/bilf/deck',
        s3Key: 'deck',
        projectId: projectId,
        clientId: clientId,
        userId: userId,
        size: 550000,
    },
    {
        originalName: 'ClientFeedback.mp3',
        displayName: 'Client Feedback Audio',
        type: 'audio',
        category: 'asset',
        link: 'https://s3.aws.com/bilf/feedback_audio',
        s3Key: 'feedback_audio',
        projectId: projectId,
        clientId: clientId,
        userId: userId,
        size: 420000,
    },
    {
        originalName: 'RebrandingChecklist.xlsx',
        displayName: 'Rebranding Checklist',
        type: 'spreadsheet',
        category: 'work',
        link: 'https://s3.aws.com/bilf/checklist',
        s3Key: 'checklist',
        projectId: projectId,
        clientId: clientId,
        userId: userId,
        size: 95000,
    },
    {
        originalName: 'RetainerContract.pdf',
        displayName: 'Signed Retainer Contract',
        type: 'document',
        category: 'asset',
        link: 'https://s3.aws.com/bilf/contract',
        s3Key: 'contract',
        projectId: projectId,
        clientId: clientId,
        userId: userId,
        size: 240000,
    },
    {
        originalName: 'WebsiteWireframes.fig',
        displayName: 'Wireframes for Website',
        type: 'design',
        category: 'work',
        link: 'https://s3.aws.com/bilf/wireframes',
        s3Key: 'wireframes',
        projectId: projectId,
        clientId: clientId,
        userId: userId,
        size: 830000,
    },
    {
        originalName: 'SocialMediaKit.zip',
        displayName: 'Social Media Kit',
        type: 'archive',
        category: 'asset',
        link: 'https://s3.aws.com/bilf/sm_kit',
        s3Key: 'sm_kit',
        projectId: projectId,
        clientId: clientId,
        userId: userId,
        size: 720000,
    },
    {
        originalName: 'LetterheadTemplate.docx',
        displayName: 'Letterhead Template',
        type: 'document',
        category: 'work',
        link: 'https://s3.aws.com/bilf/letterhead',
        s3Key: 'letterhead',
        projectId: projectId,
        clientId: clientId,
        userId: userId,
        size: 61000,
    },
    {
        originalName: 'ClientReviewNotes.txt',
        displayName: 'Notes from Client Review',
        type: 'document',
        category: 'work',
        link: 'https://s3.aws.com/bilf/review_notes',
        s3Key: 'review_notes',
        projectId: projectId,
        clientId: clientId,
        userId: userId,
        size: 18000,
    },
    {
        originalName: 'LogoAnimation.mp4',
        displayName: 'Logo Animation',
        type: 'video',
        category: 'asset',
        link: 'https://s3.aws.com/bilf/logo_anim',
        s3Key: 'logo_anim',
        projectId: projectId,
        clientId: clientId,
        userId: userId,
        size: 1400000,
    },
    {
        originalName: 'MeetingTranscript.docx',
        displayName: 'Transcript of Kickoff Meeting',
        type: 'document',
        category: 'work',
        link: 'https://s3.aws.com/bilf/kickoff_transcript',
        s3Key: 'kickoff_transcript',
        projectId: projectId,
        clientId: clientId,
        userId: userId,
        size: 95000,
    },
    {
        originalName: 'CaseStudyTemplate.pptx',
        displayName: 'Case Study Template',
        type: 'presentation',
        category: 'asset',
        link: 'https://s3.aws.com/bilf/casestudy',
        s3Key: 'casestudy',
        projectId: projectId,
        clientId: clientId,
        userId: userId,
        size: 300000,
    },
    {
        originalName: 'QA_Feedback.xlsx',
        displayName: 'QA Feedback Sheet',
        type: 'spreadsheet',
        category: 'work',
        link: 'https://s3.aws.com/bilf/qa_feedback',
        s3Key: 'qa_feedback',
        projectId: projectId,
        clientId: clientId,
        userId: userId,
        size: 88000,
    },
    {
        originalName: 'OldBrandAssets.zip',
        displayName: 'Legacy Brand Files',
        type: 'archive',
        category: 'asset',
        link: 'https://s3.aws.com/bilf/old_assets',
        s3Key: 'old_assets',
        projectId: projectId,
        clientId: clientId,
        userId: userId,
        size: 2048576,
    },
];
